Config = {
    ["UsingLoader"]     = false,
    
    ["UsingESX"]        = true,
    ["UsingESX_V1.2.0"] = false,
    ["UsingKashacters"] = true,
    ["CashAccountName"] = "money",
    ["BankAccountName"] = "bank",
}

Controls = {
  Focus = 185,
  Grab = 24,
}

furni = {}

furni.objects = {
  ["Couches"] = {
    [1] = { ["object"] = "miss_rub_couch_01", ["price"] = 80, ["name"] = "Old Flowered Couch" },
    [2] = { ["object"] = "prop_fib_3b_bench", ["price"] = 200, ["name"] = "Hospital Bench" },
    [3] = { ["object"] = "prop_ld_farm_chair01", ["price"] = 60, ["name"] = "Old Grey Seat Couch" },
    [4] = { ["object"] = "prop_ld_farm_couch01", ["price"] = 140, ["name"] = "Old Grey Couch" },
    [5] = { ["object"] = "prop_ld_farm_couch02", ["price"] = 130, ["name"] = "Old Striped Couch" },
    [6] = { ["object"] = "v_res_d_armchair", ["price"] = 90, ["name"] = "Old 1 Green Seat Couch" },
    [7] = { ["object"] = "v_res_fh_sofa", ["price"] = 1200, ["name"] = "White Corner Sofa" },
    [8] = { ["object"] = "v_res_mp_sofa", ["price"] = 1300, ["name"] = "White Corner Sofa with lamp" },
    [9] = { ["object"] = "v_res_d_sofa", ["price"] = 300, ["name"] = "Plastic Wrapped Couch" },
    [10] = { ["object"] = "v_res_j_sofa", ["price"] = 275, ["name"] = "Floral Couch" },
    [11] = { ["object"] = "v_res_mp_stripchair", ["price"] = 100, ["name"] = "Green Seat Couch" },
    [12] = { ["object"] = "v_res_m_h_sofa_sml", ["price"] = 400, ["name"] = "Vintage Sofa" },
    [13] = { ["object"] = "v_res_r_sofa", ["price"] = 560, ["name"] = "Stripped Vintage Sofa" },
    [14] = { ["object"] = "v_res_tre_sofa", ["price"] = 95, ["name"] = "Old Blue Sofa" },
    [15] = { ["object"] = "v_res_tre_sofa_mess_a", ["price"] = 50, ["name"] = "Stained Blue Sofa" },
    [16] = { ["object"] = "v_res_tre_sofa_mess_b", ["price"] = 45, ["name"] = "Moldy Blue Sofa" },
    [17] = { ["object"] = "v_res_tre_sofa_mess_c", ["price"] = 30, ["name"] = "Torn Blue Sofa" },
    [18] = { ["object"] = "v_res_tt_sofa", ["price"] = 130, ["name"] = "Plaid Wood Sofa" },
    [19] = { ["object"] = "prop_couch_01", ["price"] = 400, ["name"] = "Comfy Leather Couch" },
    [20] = { ["object"] = "apa_mp_h_stn_foot_stool_02", ["price"] = 130, ["name"] = "White Foot Stool" },
    [21] = { ["object"] = "apa_mp_h_stn_foot_stool_01", ["price"] = 120, ["name"] = "Grey Foot Stool" },
    [22] = { ["object"] = "v_ilev_m_sofa", ["price"] = 1100, ["name"] = "Medium White Corner Couch" },
    [23] = { ["object"] = "prop_couch_lg_05", ["price"] = 250, ["name"] = "Grey Fabric Couch" },
    [24] = { ["object"] = "apa_mp_h_stn_sofacorn_05", ["price"] = 350, ["name"] = "Grey Modern Corner Sofa" },
    [25] = { ["object"] = "prop_couch_sm_07", ["price"] = 140, ["name"] = "White Modern Seat Couch" },
    [26] = { ["object"] = "prop_couch_lg_06", ["price"] = 500, ["name"] = "Brown Leather Couch" },
    [27] = { ["object"] = "p_yacht_sofa_01_s", ["price"] = 200, ["name"] = "Yacht sofa" },
    [28] = { ["object"] = "prop_couch_sm_06", ["price"] = 700, ["name"] = "Brown Leather Seat Couch" },
    [29] = { ["object"] = "prop_couch_lg_07", ["price"] = 470, ["name"] = "White Modern Couch" },
    [30] = { ["object"] = "apa_mp_h_stn_sofacorn_01", ["price"] = 700, ["name"] = "Corner Sofa 1" },
    [31] = { ["object"] = "apa_mp_h_stn_sofacorn_05", ["price"] = 700, ["name"] = "Corner Sofa 2" },
    [32] = { ["object"] = "apa_mp_h_stn_sofacorn_06", ["price"] = 700, ["name"] = "Corner Sofa 3" },
    [33] = { ["object"] = "apa_mp_h_stn_sofacorn_07", ["price"] = 700, ["name"] = "Corner Sofa 4" },
    [34] = { ["object"] = "apa_mp_h_stn_sofacorn_08", ["price"] = 700, ["name"] = "Corner Sofa 5" },
    [35] = { ["object"] = "apa_mp_h_stn_sofacorn_09", ["price"] = 700, ["name"] = "Corner Sofa 6" },
    [36] = { ["object"] = "apa_mp_h_stn_sofacorn_10", ["price"] = 700, ["name"] = "Corner Sofa 7" },
    [37] = { ["object"] = "apa_mp_h_stn_sofa_daybed_01", ["price"] = 200, ["name"] = "Daybed 1" },
    [38] = { ["object"] = "apa_mp_h_stn_sofa_daybed_02", ["price"] = 200, ["name"] = "Daybed 2" },
    [39] = { ["object"] = "apa_mp_h_stn_sofa2seat_02", ["price"] = 400, ["name"] = "Sofa 2 Seat" },
    [40] = { ["object"] = "ex_mp_h_off_sofa_01", ["price"] = 600, ["name"] = "White Leather Sofa" },
    [41] = { ["object"] = "ex_mp_h_off_sofa_02", ["price"] = 600, ["name"] = "Black Leather Sofa" },
    [42] = { ["object"] = "ex_mp_h_off_sofa_003", ["price"] = 600, ["name"] = "Grey Leather Sofa" },
  },

  ["Chairs"] = {
    [1] = { ["object"] = "v_res_d_highchair", ["price"] = 40, ["name"] = "High Chair" },
    [2] = { ["object"] = "v_res_fa_chair01", ["price"] = 60, ["name"] = " Wood Chair" },
    [3] = { ["object"] = "prop_chair_04a", ["price"] = 70, ["name"] = "Retro Wood Dine Chair" },
    [4] = { ["object"] = "v_res_fh_barcchair", ["price"] = 90, ["name"] = "Blck Modern Leather Chair" },
    [5] = { ["object"] = "v_res_fh_dineeamesa", ["price"] = 50, ["name"] = "Blue Dine Chair" },
    [6] = { ["object"] = "v_res_fh_dineeamesb", ["price"] = 50, ["name"] = "Yellow Dine Chair" },
    [7] = { ["object"] = "v_res_fh_dineeamesc", ["price"] = 50, ["name"] = "Grey Dine Chair" },
    [8] = { ["object"] = "prop_chair_04b", ["price"] = 80, ["name"] = "White Modern Dine Chair" },
    [9] = { ["object"] = "v_res_fh_kitnstool", ["price"] = 60, ["name"] = "Grey Stool" },
    [10] = { ["object"] = "v_res_fh_singleseat", ["price"] = 130, ["name"] = "Red Reading Chair" },
    [11] = { ["object"] = "v_res_jarmchair", ["price"] = 70, ["name"] = "Velvet Retro Armchair" },
    [12] = { ["object"] = "v_res_j_dinechair", ["price"] = 30, ["name"] = "Torn Dining Chair" },
    [13] = { ["object"] = "prop_chair_08", ["price"] = 20, ["name"] = "White Plastic Dine Chair" },
    [14] = { ["object"] = "v_res_mbchair", ["price"] = 110, ["name"] = "White Modern Conference Chair" },
    [15] = { ["object"] = "v_res_m_armchair", ["price"] = 175, ["name"] = "White Arm Chair" },
    [16] = { ["object"] = "v_res_m_dinechair", ["price"] = 50, ["name"] = "Plain Wood Dine Chair" },
    [17] = { ["object"] = "v_res_study_chair", ["price"] = 40, ["name"] = "Study Chair" },
    [18] = { ["object"] = "v_res_trev_framechair", ["price"] = 35, ["name"] = "Frame Chair" },
    [19] = { ["object"] = "v_res_tre_chair", ["price"] = 48, ["name"] = "Farmhouse Dine Chair" },
    [20] = { ["object"] = "prop_chair_05", ["price"] = 170, ["name"] = "Wicker Chair" },
    [21] = { ["object"] = "v_res_tre_stool", ["price"] = 50, ["name"] = "Round Stool" },
    [22] = { ["object"] = "v_res_tre_stool_leather", ["price"] = 55, ["name"] = "Round Leather Stool" },
    [23] = { ["object"] = "v_res_tre_stool_scuz", ["price"] = 35, ["name"] = "Torn Leather Stool" },
    [24] = { ["object"] = "v_med_p_deskchair", ["price"] = 70, ["name"] = "Leather Desk Chair" },
    [25] = { ["object"] = "v_med_p_easychair", ["price"] = 80, ["name"] = "Grey Modern Chair" },
    [26] = { ["object"] = "v_med_whickerchair1", ["price"] = 75, ["name"] = "Retro Fabric Chair" },
    [27] = { ["object"] = "prop_chateau_chair_01", ["price"] = 130, ["name"] = "Hawaiian Wicker Chair" },
    [28] = { ["object"] = "prop_direct_chair_02", ["price"] = 95, ["name"] = "Director Chair" },
    [29] = { ["object"] = "prop_yacht_lounger", ["price"] = 80, ["name"] = "Lounge Yacht Chair" },
    [30] = { ["object"] = "prop_yacht_seat_01", ["price"] = 99, ["name"] = "Stripped Yacht Chair" },
    [31] = { ["object"] = "prop_yacht_seat_02", ["price"] = 140, ["name"] = "Stripped Yacht Couch" },
    [32] = { ["object"] = "prop_yacht_seat_03", ["price"] = 80, ["name"] = "Striped Yacht Seat" },
    [33] = { ["object"] = "v_ret_chair_white", ["price"] = 150, ["name"] = "Royal White Chair" },
    [34] = { ["object"] = "v_ret_chair", ["price"] = 160, ["name"] = "Red Royal Chair" },
    [35] = { ["object"] = "v_ret_ta_stool", ["price"] = 45, ["name"] = "Bathroom Stool" },
    [36] = { ["object"] = "prop_off_chair_01", ["price"] = 120, ["name"] = "Blck Office Chair" },
    [37] = { ["object"] = "prop_table_02_chr", ["price"] = 70, ["name"] = "Cabin Dine Chair" },
    [38] = { ["object"] = "prop_cs_folding_chair_01", ["price"] = 40, ["name"] = "Folding Chair" },
    [39] = { ["object"] = "prop_rock_chair_01", ["price"] = 30, ["name"] = "Rocking Chair" },
    [40] = { ["object"] = "prop_wheelchair_01", ["price"] = 60, ["name"] = "Wheelchair" },
    [41] = { ["object"] = "p_clb_officechair_s", ["price"] = 200, ["name"] = "Comfy Office Chair" },
    [42] = { ["object"] = "prop_off_chair_04_s", ["price"] = 100, ["name"] = "Plain Office Chair" },
    [43] = { ["object"] = "prop_off_chair_04", ["price"] = 70, ["name"] = "Old Office Chair" },
    [44] = { ["object"] = "prop_off_chair_03", ["price"] = 30, ["name"] = "Moldy Office Chair" },
    [45] = { ["object"] = "v_corp_offchair", ["price"] = 85, ["name"] = "Staples Office Chair" },
    [46] = { ["object"] = "prop_torture_ch_01", ["price"] = 38, ["name"] = "Torture Chair" },
    [47] = { ["object"] = "p_dinechair_01_s", ["price"] = 135, ["name"] = "Majestic Chair" },
    [48] = { ["object"] = "p_soloffchair_s", ["price"] = 180, ["name"] = "Worn Executive Office Chair" },
    [49] = { ["object"] = "prop_sol_chair", ["price"] = 230, ["name"] = "New Executive Office Chair" },
    [50] = { ["object"] = "prop_gc_chair02", ["price"] = 42, ["name"] = "Worn School Chair" },
    [51] = { ["object"] = "v_ilev_chair02_ped", ["price"] = 700, ["name"] = "New School Chair" },
    [52] = { ["object"] = "v_corp_cd_chair", ["price"] = 700, ["name"] = "Worn Red Office Chair" },
    [53] = { ["object"] = "v_corp_bk_chair3", ["price"] = 90, ["name"] = "Corporate Office Chair" },
    [54] = { ["object"] = "prop_skid_chair_03", ["price"] = 25, ["name"] = "Plaid Folding Chair" },
    [55] = { ["object"] = "prop_table_01_chr_a", ["price"] = 80, ["name"] = "Wood Table Chair" },
    [56] = { ["object"] = "prop_table_01_chr_b", ["price"] = 75, ["name"] = "Wood Table Chair 2" },
    [57] = { ["object"] = "prop_table_04_chr", ["price"] = 65, ["name"] = "Lounge Chair" },
    [58] = { ["object"] = "prop_table_05_chr", ["price"] = 95, ["name"] = "Wicker Lounge Chair" },
    [59] = { ["object"] = "apa_mp_h_din_chair_04", ["price"] = 85, ["name"] = "Comfy Modern Dine Chair" },
    [60] = { ["object"] = "apa_mp_h_din_chair_08", ["price"] = 90, ["name"] = "Comfy Modern Dine Chair 2" },
    [61] = { ["object"] = "apa_mp_h_din_chair_12", ["price"] = 80, ["name"] = "Wooden Modern Dine Chair" },
    [62] = { ["object"] = "apa_mp_h_din_stool_04", ["price"] = 65, ["name"] = "White Modern Stool" },
    [63] = { ["object"] = "ex_mp_h_stn_chairstrip_05", ["price"] = 250, ["name"] = "White Modern Chair" },
    [64] = { ["object"] = "ex_mp_h_stn_chairstrip_07", ["price"] = 250, ["name"] = "Blck Modern Chair" },
    [65] = { ["object"] = "ex_mp_h_stn_chairstrip_011", ["price"] = 250, ["name"] = "White Modern Chair 2" },
    [66] = { ["object"] = "ex_mp_h_stn_chairstrip_010", ["price"] = 250, ["name"] = "Brown Modern Chair 2" },
    [67] = { ["object"] = "ex_mp_h_stn_chairstrip_01", ["price"] = 170, ["name"] = "Orange Reading Chair" },
    [68] = { ["object"] = "ex_mp_h_stn_chairarm_24", ["price"] = 165, ["name"] = "Blck Leather Conference Chair" },
    [69] = { ["object"] = "ex_mp_h_stn_chairarm_03", ["price"] = 130, ["name"] = "Retro Conference Chair" },
    [70] = { ["object"] = "ex_mp_h_yacht_barstool_01", ["price"] = 50, ["name"] = "White Retro Barstool" },
    [71] = { ["object"] = "v_corp_facebeanbag", ["price"] = 30, ["name"] = "Bean Bag 1" },
    [72] = { ["object"] = "apa_mp_h_stn_chairarm_13", ["price"] = 400, ["name"] = "Yellowchair" },
    [73] = { ["object"] = "prop_armchair_01", ["price"] = 300, ["name"] = "Neutral Armchair" },
  },

  ["Beds"] = {
    [1] = { ["object"] = "v_res_d_bed", ["price"] = 400, ["name"] = "Leopard Print Bed" },  
    [2] = { ["object"] = "v_res_lestersbed", ["price"] = 500, ["name"] = "Messy Standard Bed" }, 
    [3] = { ["object"] = "v_res_mbbed", ["price"] = 700, ["name"] = "Spanish Villa Bed" }, 
    [4] = { ["object"] = "v_res_mdbed", ["price"] = 600, ["name"] = "Royal Bed" }, 
    [5] = { ["object"] = "v_res_msonbed", ["price"] = 700, ["name"] = "Modern Mason Bed" },  
    [6] = { ["object"] = "v_res_tre_bed1", ["price"] = 550, ["name"] = "Beach House Bed" }, 
    [7] = { ["object"] = "v_res_tre_bed2", ["price"] = 300, ["name"] = "Plain Bed" }, 
    [8] = { ["object"] = "v_res_tt_bed", ["price"] = 200, ["name"] = "Dirty Bed" },
    [9] = { ["object"] = "apa_mp_h_bed_double_08", ["price"] = 720, ["name"] = "Hotel Bed" },  
    [10] = { ["object"] = "apa_mp_h_bed_double_09", ["price"] = 800, ["name"] = "Modern Bed 2" },
    [11] = { ["object"] = "apa_mp_h_bed_wide_05", ["price"] = 750, ["name"] = "Modern Bed 3" },
    [12] = { ["object"] = "apa_mp_h_bed_with_table_02", ["price"] = 1000, ["name"] = "Bed with table" },
    [13] = { ["object"] = "gr_prop_bunker_bed_01", ["price"] = 170, ["name"] = "Single bed" },
  },

  
  ["Cash Gold and Jewels"] = {
    [1] = { ["object"] = "prop_jewel_03b", ["price"] = 100, ["name"] = "Jewel 1" },
    [2] = { ["object"] = "prop_jewel_04b", ["price"] = 200, ["name"] = "Jewel 2" },
    [3] = { ["object"] = "prop_jewel_02b", ["price"] = 200, ["name"] = "Jewel 3" },
    [4] = { ["object"] = "prop_jewel_pickup_new_01", ["price"] = 200, ["name"] = "Jewel 4" },
    [5] = { ["object"] = "prop_jewel_02a", ["price"] = 200, ["name"] = "Jewel 5" },
    [6] = { ["object"] = "prop_jewel_02c", ["price"] = 200, ["name"] = "Jewel 6" },
    [7] = { ["object"] = "prop_jewel_03a", ["price"] = 200, ["name"] = "Jewel 7" },
    [8] = { ["object"] = "prop_jewel_04a", ["price"] = 200, ["name"] = "Jewel 8" },
    [9] = { ["object"] = "p_watch_01", ["price"] = 100, ["name"] = "Watch 1" },
    [10] = { ["object"] = "p_watch_02", ["price"] = 100, ["name"] = "Watch 2" },
    [11] = { ["object"] = "p_watch_03", ["price"] = 100, ["name"] = "Watch 3" },
    [12] = { ["object"] = "p_watch_04", ["price"] = 100, ["name"] = "Watch 4" },
    [13] = { ["object"] = "p_watch_05", ["price"] = 100, ["name"] = "Watch 5" },
    [14] = { ["object"] = "p_watch_06", ["price"] = 100, ["name"] = "Watch 6" },
    [15] = { ["object"] = "prop_cash_case_02", ["price"] = 500, ["name"] = "Cash Case" },
    [16] = { ["object"] = "prop_cash_crate_01", ["price"] = 700, ["name"] = "Cash Crate" },
    [17] = { ["object"] = "hei_prop_cash_crate_half_full", ["price"] = 700, ["name"] = "Cash Crate 2" },
    [18] = { ["object"] = "prop_anim_cash_note_b", ["price"] = 1, ["name"] = "Cash Note" },
    [19] = { ["object"] = "prop_anim_cash_pile_01", ["price"] = 100, ["name"] = "Cash Pile" },
    [20] = { ["object"] = "prop_cash_trolly", ["price"] = 300, ["name"] = "Cash Trolly" },
    [21] = { ["object"] = "prop_poly_bag_money", ["price"] = 200, ["name"] = "Money Bag" },
    [22] = { ["object"] = "prop_gold_trolly_full", ["price"] = 700, ["name"] = "Gold Trolly" },
    [23] = { ["object"] = "prop_gold_trolly", ["price"] = 100, ["name"] = "Gold Trolly 2" },
    [24] = { ["object"] = "prop_gold_bar", ["price"] = 100, ["name"] = "Gold Bar" },
    [25] = { ["object"] = "prop_large_gold", ["price"] = 1000, ["name"] = "Large Gold" },
    [26] = { ["object"] = "bkr_prop_bkr_cashpile_04", ["price"] = 1000, ["name"] = "Bigger Cashpile" },
    [27] = { ["object"] = "prop_ld_gold_chest", ["price"] = 500, ["name"] = "Gold Chest" },
    [28] = { ["object"] = "prop_idol_case_01", ["price"] = 100, ["name"] = "Idol Case" },
    [29] = { ["object"] = "prop_j_disptray_01", ["price"] = 300, ["name"] = "Display Tray" },
    [30] = { ["object"] = "prop_j_disptray_01b", ["price"] = 300, ["name"] = "Display Tray" },
    [31] = { ["object"] = "prop_j_disptray_02", ["price"] = 300, ["name"] = "Display Tray" },
    [32] = { ["object"] = "prop_j_disptray_03", ["price"] = 300, ["name"] = "Display Tray" },
    [33] = { ["object"] = "prop_j_disptray_04", ["price"] = 300, ["name"] = "Display Tray" },
    [34] = { ["object"] = "prop_j_disptray_04b", ["price"] = 300, ["name"] = "Display Tray" },
    [35] = { ["object"] = "prop_j_disptray_05", ["price"] = 300, ["name"] = "Display Tray" },
    [36] = { ["object"] = "prop_j_disptray_05b", ["price"] = 300, ["name"] = "Display Tray" },
    [37] = { ["object"] = "v_res_jewelbox", ["price"] = 400, ["name"] = "Jewel Box" },
    [38] = { ["object"] = "prop_peyote_gold_01", ["price"] = 200, ["name"] = "Peyote Gold" },
    [39] = { ["object"] = "prop_cs_cash_note_01", ["price"] = 100, ["name"] = "Cash Note 2" },
    [40] = { ["object"] = "bkr_prop_bkr_cashpile_01", ["price"] = 500, ["name"] = "Cash Pile" },
    [41] = { ["object"] = "bkr_prop_bkr_cash_roll_01", ["price"] = 100, ["name"] = "Group Rolled Dollars" },
    [42] = { ["object"] = "bkr_prop_money_unsorted_01", ["price"] = 100, ["name"] = "Stacked Dollar Bills" },
  },

  ["Drugs"] = {
    [1] = { ["object"] = "prop_weed_pallet", ["price"] = 600, ["name"] = "Weed Pallet" },
    [2] = { ["object"] = "hei_prop_hei_drug_pack_01b", ["price"] = 200, ["name"] = "Coke Brick" },
    [3] = { ["object"] = "hei_prop_hei_drug_pack_01a", ["price"] = 150, ["name"] = "Small Coke Brick" },
    [4] = { ["object"] = "hei_prop_hei_drug_pack_02", ["price"] = 100, ["name"] = "Coke Pouch" },
    [5] = { ["object"] = "hei_prop_heist_drug_tub_01", ["price"] = 80, ["name"] = "Rubbermaid" },
    [6] = { ["object"] = "ng_proc_drug01a002", ["price"] = 80, ["name"] = "Pill Bottle" },
    [7] = { ["object"] = "prop_drug_bottle", ["price"] = 90, ["name"] = "Chemical Jug" },
    [8] = { ["object"] = "hei_prop_hei_drug_case", ["price"] = 130, ["name"] = "Coke Breifcase" },
    [9] = { ["object"] = "prop_drug_burner", ["price"] = 120, ["name"] = "Burner" },
    [10] = { ["object"] = "prop_drug_package", ["price"] = 100, ["name"] = "Package" },
    [11] = { ["object"] = "prop_drug_package_02", ["price"] = 80, ["name"] = "Package Smol" },
    [12] = { ["object"] = "ex_office_swag_drugbags", ["price"] = 80, ["name"] = "Drug Bag Small" },
    [13] = { ["object"] = "prop_cs_crackpipe", ["price"] = 30, ["name"] = "Crack Pipe" },
    [14] = { ["object"] = "prop_cs_pills", ["price"] = 30, ["name"] = "Prescription 4" },
    [15] = { ["object"] = "prop_coke_block_01", ["price"] = 30, ["name"] = "Open Coke Brick" },
    [16] = { ["object"] = "prop_coke_block_half_a", ["price"] = 100, ["name"] = "Open Coke Block Half" },
    [17] = { ["object"] = "p_meth_bag_01_s", ["price"] = 100, ["name"] = "Meth Bag" },
    [18] = { ["object"] = "ex_office_swag_drugbag2", ["price"] = 300, ["name"] = "Drug Bag Large" },
    [19] = { ["object"] = "prop_meth_setup_01", ["price"] = 100, ["name"] = "Meth Lab" },
    [20] = { ["object"] = "prop_cs_script_bottle_01", ["price"] = 100, ["name"] = "Script Bottle" },
    [21] = { ["object"] = "prop_cs_script_bottle", ["price"] = 100, ["name"] = "Script Bottle 2" },
    [22] = { ["object"] = "prop_cigar_pack_01", ["price"] = 19, ["name"] = "Cigar Pack 1" },
    [23] = { ["object"] = "prop_cigar_pack_02", ["price"] = 190, ["name"] = "Cigar Pack 2" },
    [24] = { ["object"] = "v_res_m_kscales", ["price"] = 100, ["name"] = "Scales" },
    [25] = { ["object"] = "ng_proc_cigarette01a", ["price"] = 8, ["name"] = "Cigarette 1" },
    [26] = { ["object"] = "ng_proc_cigbuts01a", ["price"] = 8, ["name"] = "Cigarette 2" },
    [27] = { ["object"] = "ng_proc_cigpak01a", ["price"] = 8, ["name"] = "Cigarette Pack 1" },
    [28] = { ["object"] = "ng_proc_cigpak01b", ["price"] = 8, ["name"] = "Cigarette Pack 2" },
    [29] = { ["object"] = "ng_proc_syrnige01a", ["price"] = 90, ["name"] = "Syringe" },
    [30] = { ["object"] = "p_cs_joint_01", ["price"] = 20, ["name"] = "Joint" },
    [31] = { ["object"] = "p_cs_joint_02", ["price"] = 25, ["name"] = "Joint 2" },
    [32] = { ["object"] = "p_cs_coke_line_s", ["price"] = 60, ["name"] = "Coke Line" },
    [33] = { ["object"] = "p_cs_lighter_01", ["price"] = 15, ["name"] = "Lighter" },
    [34] = { ["object"] = "prop_cs_meth_pipe", ["price"] = 30, ["name"] = "Meth Pipe" },
    [35] = { ["object"] = "bkr_prop_coke_powder_02", ["price"] = 200, ["name"] = "Coke Pile" },
    [36] = { ["object"] = "bkr_prop_weed_bag_01a", ["price"] = 10, ["name"] = "Empty Weed Bag" },
    [37] = { ["object"] = "bkr_prop_weed_bigbag_open_01a", ["price"] = 200, ["name"] = "Weed Bag Open" },
    [38] = { ["object"] = "bkr_prop_weed_bigbag_03a", ["price"] = 100, ["name"] = "Weed Big Bag" },
    [39] = { ["object"] = "bkr_prop_meth_openbag_01a", ["price"] = 100, ["name"] = "Open Meth Bag" },
    [40] = { ["object"] = "bkr_prop_coke_cutblock_01", ["price"] = 100, ["name"] = "Cocaine Block" },
    [41] = { ["object"] = "bkr_prop_fakeid_bundledriverl", ["price"] = 80, ["name"] = "Fake IDs" },
    [42] = { ["object"] = "prop_cs_credit_card", ["price"] = 60, ["name"] = "Credit Card" },
    [43] = { ["object"] = "prop_sh_bong_01", ["price"] = 60, ["name"] = "Bong" },
    [44] = { ["object"] = "v_ret_fh_ashtray", ["price"] = 30, ["name"] = "Dirty Ashtray" },
    [45] = { ["object"] = "v_res_mp_ashtrayb", ["price"] = 30, ["name"] = "Ashtray" },
    [46] = { ["object"] = "prop_cigar_01", ["price"] = 20, ["name"] = "Cigar" },
  },

  ["Food and Drinks"] = {
    [1] = { ["object"] = "prop_peanut_bowl_01", ["price"] = 5, ["name"] = "Peanut Bowl" },
    [2] = { ["object"] = "prop_cs_bowl_01", ["price"] = 10, ["name"] = "Bowl" },
    [3] = { ["object"] = "prop_cs_bs_cup", ["price"] = 12, ["name"] = "Cup" },
    [4] = { ["object"] = "prop_fruit_stand_03", ["price"] = 300, ["name"] = "Fruit Stand 1" },
    [5] = { ["object"] = "prop_fruit_stand_02", ["price"] = 300, ["name"] = "Fruit Stand 2" },
    [6] = { ["object"] = "prop_fruit_stand_01", ["price"] = 300, ["name"] = "Fruit Stand 3" },
    [7] = { ["object"] = "prop_cs_beer_box", ["price"] = 40, ["name"] = "Beer Box" },
    [8] = { ["object"] = "prop_beer_box_01", ["price"] = 40, ["name"] = "Beer Box 2" },
    [9] = { ["object"] = "beerrow_world", ["price"] = 80, ["name"] = "Beer Group" },
    [10] = { ["object"] = "prop_amb_beer_bottle", ["price"] = 8, ["name"] = "Pisswater" },
    [11] = { ["object"] = "prop_beer_blr", ["price"] = 8, ["name"] = "Blarney's" },
    [12] = { ["object"] = "prop_beer_logger", ["price"] = 8, ["name"] = "Logger" },
    [13] = { ["object"] = "prop_cs_plate_01", ["price"] = 15, ["name"] = "Plate With Food" },
    [14] = { ["object"] = "prop_cs_crisps_01", ["price"] = 10, ["name"] = "Bag of Chips" },
    [15] = { ["object"] = "prop_donut_01", ["price"] = 6, ["name"] = "Doughnut" },
    [16] = { ["object"] = "ex_office_swag_booze_cigs2", ["price"] = 200, ["name"] = "Vodka and Cigars" },
    [17] = { ["object"] = "xm_prop_x17_coffee_jug", ["price"] = 100, ["name"] = "Coffee Pot" },
    [18] = { ["object"] = "prop_whiskey_01", ["price"] = 30, ["name"] = "Glass Empty Whiskey" },
    [19] = { ["object"] = "prop_drink_whtwine", ["price"] = 40, ["name"] = "Full White Wine Glass" },
    [20] = { ["object"] = "prop_drink_whisky", ["price"] = 40, ["name"] = "Full Whiskey Glass" },
    [21] = { ["object"] = "ng_proc_food_bag01a", ["price"] = 10, ["name"] = "Burger Bag" },
    [22] = { ["object"] = "prop_food_bs_burg1", ["price"] = 10, ["name"] = "Package Burger" },
    [23] = { ["object"] = "prop_food_bs_burg3", ["price"] = 10, ["name"] = "Boxed Burger" },
    [24] = { ["object"] = "prop_food_bs_chips", ["price"] = 10, ["name"] = "French Fries" },
    [25] = { ["object"] = "prop_food_bs_burger2", ["price"] = 10, ["name"] = "Wrapped Sub" },
    [26] = { ["object"] = "prop_food_bs_coffee", ["price"] = 10, ["name"] = "ToGo Drink" },
    [27] = { ["object"] = "prop_food_cups1", ["price"] = 10, ["name"] = "Paper Cup Stack Red" },
    [28] = { ["object"] = "prop_food_cb_cups01", ["price"] = 10, ["name"] = "Paper Cup Stack Yellow" },
    [29] = { ["object"] = "prop_food_cb_cups02", ["price"] = 10, ["name"] = "GroupStack of Cups" },
    [30] = { ["object"] = "prop_food_bs_cups02", ["price"] = 10, ["name"] = "Food 10" },
    [31] = { ["object"] = "prop_orang_can_01", ["price"] = 10, ["name"] = "Soda Can 3" },
    [32] = { ["object"] = "prop_drink_champ", ["price"] = 40, ["name"] = "Full Champagne Glass" },
    [33] = { ["object"] = "prop_tumbler_01", ["price"] = 40, ["name"] = "Tumbler" },
    [34] = { ["object"] = "prop_lime_jar", ["price"] = 40, ["name"] = "Lime Jar" },
    [35] = { ["object"] = "prop_bowl_crisps", ["price"] = 20, ["name"] = "Bowl Crisps" },
    [36] = { ["object"] = "prop_candy_pqs", ["price"] = 20, ["name"] = "Candy" },
    [37] = { ["object"] = "prop_pizza_box_03", ["price"] = 60, ["name"] = "Pizza Box 3" },
    [38] = { ["object"] = "prop_cs_whiskey_bottle", ["price"] = 70, ["name"] = "Whiskey Bottle" },
    [39] = { ["object"] = "prop_pizza_box_02", ["price"] = 60, ["name"] = "Pizza Box 2" },
    [40] = { ["object"] = "lts_prop_wine_glass_s2", ["price"] = 40, ["name"] = "Wine Glass" },
    [41] = { ["object"] = "ng_proc_sodacan_01a", ["price"] = 10, ["name"] = "Cola Can" },
    [42] = { ["object"] = "ng_proc_sodacan_01b", ["price"] = 10, ["name"] = "Sprunk Can" },
    [43] = { ["object"] = "ng_proc_sodabot_01a", ["price"] = 10, ["name"] = "Soda Bottle" },
    [44] = { ["object"] = "ng_proc_coffee_01a", ["price"] = 10, ["name"] = "Coffee Cup" },
    [45] = { ["object"] = "hei_p_hei_champ_flute_s", ["price"] = 40, ["name"] = "Champagne Glass" },
    [46] = { ["object"] = "p_w_grass_gls_s", ["price"] = 20, ["name"] = "Green Juice" },
    [47] = { ["object"] = "prop_drink_redwine", ["price"] = 40, ["name"] = "Glass Red Wine" },
    [48] = { ["object"] = "prop_bar_cockshaker", ["price"] = 70, ["name"] = "Cocktail Shaker 1" },
    [49] = { ["object"] = "prop_bar_cockshakropn", ["price"] = 70, ["name"] = "Cocktail Shaker 2" },
    [50] = { ["object"] = "prop_bar_shots", ["price"] = 100, ["name"] = "Shots" },
    [51] = { ["object"] = "p_cs_shot_glass_2_s", ["price"] = 100, ["name"] = "Shot Glass" },
    [52] = { ["object"] = "prop_bottle_brandy", ["price"] = 100, ["name"] = "Brandy" },
    [53] = { ["object"] = "prop_bottle_macbeth", ["price"] = 100, ["name"] = "Macbeth" },
    [54] = { ["object"] = "prop_brandy_glass", ["price"] = 100, ["name"] = "Brandy Glass" },
    [55] = { ["object"] = "prop_cava", ["price"] = 100, ["name"] = "Wine Bottle" },
    [56] = { ["object"] = "prop_champ_01a", ["price"] = 100, ["name"] = "Champagne Bottle" },
    [57] = { ["object"] = "prop_champset", ["price"] = 100, ["name"] = "Champagne Set" },
    [58] = { ["object"] = "prop_cherenkov_01", ["price"] = 100, ["name"] = "Vodka 1" },
    [59] = { ["object"] = "prop_cherenkov_02", ["price"] = 100, ["name"] = "Vodka 2" },
    [60] = { ["object"] = "prop_cocktail", ["price"] = 100, ["name"] = "Cocktail" },
    [61] = { ["object"] = "prop_cocktail_glass", ["price"] = 100, ["name"] = "Cocktail Glass" },
    [62] = { ["object"] = "prop_cs_burger_01", ["price"] = 10, ["name"] = "Burger" },
    [63] = { ["object"] = "winerow", ["price"] = 200, ["name"] = "Wine Row" },
    [64] = { ["object"] = "vodkarow", ["price"] = 200, ["name"] = "Vodka Row" },
    [65] = { ["object"] = "v_serv_bs_mug", ["price"] = 20, ["name"] = "Coffee Mug" },
    [66] = { ["object"] = "v_ret_247_ketchup2", ["price"] = 10, ["name"] = "Ketchup" },
    [67] = { ["object"] = "v_ret_247_noodle1", ["price"] = 10, ["name"] = "Instant Noodles" },
    [68] = { ["object"] = "prop_whiskey_glasses", ["price"] = 70, ["name"] = "Whiskey Glasses" },
    [69] = { ["object"] = "prop_whiskey_bottle", ["price"] = 100, ["name"] = "Whiskey Bottle" },
    [70] = { ["object"] = "prop_wine_red", ["price"] = 100, ["name"] = "Red Wine Bottle" },
    [71] = { ["object"] = "prop_wine_rose", ["price"] = 100, ["name"] = "Rose Wine Bottle" },
    [72] = { ["object"] = "prop_wine_white", ["price"] = 100, ["name"] = "White Wine Bottle" },
    [73] = { ["object"] = "prop_turkey_leg_01", ["price"] = 30, ["name"] = "Turkey Leg" },
    [74] = { ["object"] = "prop_veg_crop_03_pump", ["price"] = 30, ["name"] = "Pumpkin" },
    [75] = { ["object"] = "prop_tall_glass", ["price"] = 100, ["name"] = "Tall Glass" },
    [76] = { ["object"] = "prop_tequila", ["price"] = 100, ["name"] = "Tequila" },
    [77] = { ["object"] = "prop_tequsunrise", ["price"] = 100, ["name"] = "Tequila 2" },
    [78] = { ["object"] = "prop_tequila_bottle", ["price"] = 100, ["name"] = "Tequila Bottle" },
    [79] = { ["object"] = "prop_pineapple", ["price"] = 30, ["name"] = "Pineapple" },
    [80] = { ["object"] = "prop_pinacolada", ["price"] = 30, ["name"] = "Pina Colada" },
    [81] = { ["object"] = "prop_pizza_box_01", ["price"] = 60, ["name"] = "Pizza Box 1" },
    [82] = { ["object"] = "prop_rum_bottle", ["price"] = 100, ["name"] = "Ragga Rum Bottle" },
    [83] = { ["object"] = "prop_cherenkov_04", ["price"] = 100, ["name"] = "Cherenkov Purple Bottle" },
    [84] = { ["object"] = "prop_cherenkov_03", ["price"] = 100, ["name"] = "Cherenkov Green Bottle" },
    [85] = { ["object"] = "ba_prop_battle_champ_closed_03", ["price"] = 120, ["name"] = "Bleuter'd 1969 Bottle" },
    [86] = { ["object"] = "prop_vodka_bottle", ["price"] = 70, ["name"] = "NoGo Vodka Bottle" },
    [87] = { ["object"] = "prop_bottle_cognac", ["price"] = 70, ["name"] = "Bourgeoix Bottle" },
    [88] = { ["object"] = "prop_bottle_richard", ["price"] = 70, ["name"] = "Richard's Bottle" },
    [89] = { ["object"] = "prop_bar_fruit", ["price"] = 25, ["name"] = "Tray Sliced Fruit" },
    [90] = { ["object"] = "prop_cs_paper_cup", ["price"] = 10, ["name"] = "Paper Cup" },
    [91] = { ["object"] = "ex_mp_h_acc_fruitbowl_01", ["price"] = 25, ["name"] = "Tray Orange Apple" },
    [92] = { ["object"] = "prop_cs_steak", ["price"] = 55, ["name"] = "Steak" }, 
  },

  ["Wall Decor"] = {
    [1] = { ["object"] = "v_ilev_ra_doorsafe", ["price"] = 500, ["name"] = "Painting" },
    [2] = { ["object"] = "v_res_mchalkbrd", ["price"] = 80, ["name"] = "Chalk Board" },
    [3] = { ["object"] = "apa_p_h_acc_artwallm_04", ["price"] = 200, ["name"] = "Wall Art 1" },
    [4] = { ["object"] = "apa_p_h_acc_artwallm_03", ["price"] = 200, ["name"] = "Wall Art 2" },
    [5] = { ["object"] = "apa_p_h_acc_artwallm_01", ["price"] = 250, ["name"] = "Wall Art 3" },
    [6] = { ["object"] = "apa_p_h_acc_artwalll_04", ["price"] = 200, ["name"] = "Wall Art 4" },
    [7] = { ["object"] = "apa_p_h_acc_artwalll_03", ["price"] = 200, ["name"] = "Wall Art 5" },
    [8] = { ["object"] = "hei_prop_hei_pic_hl_valkyrie", ["price"] = 30, ["name"] = "Valkyrie" },
    [9] = { ["object"] = "hei_prop_hei_pic_pb_bus", ["price"] = 30, ["name"] = "Prison Bus" },
    [10] = { ["object"] = "hei_prop_hei_pic_pb_plane", ["price"] = 30, ["name"] = "Plane" },
    [11] = { ["object"] = "hei_prop_hei_pic_pb_station", ["price"] = 30, ["name"] = "MRPD" },
    [12] = { ["object"] = "hei_prop_hei_pic_ps_bike", ["price"] = 30, ["name"] = "Lost MC" },
    [13] = { ["object"] = "hei_prop_hei_pic_ps_job", ["price"] = 30, ["name"] = "Pacific Standard" },
    [14] = { ["object"] = "hei_prop_heist_pic_05", ["price"] = 30, ["name"] = "Helicopter" },
    [15] = { ["object"] = "hei_prop_heist_pic_06", ["price"] = 30, ["name"] = "Plane" },
    [16] = { ["object"] = "hei_prop_heist_pic_10", ["price"] = 30, ["name"] = "Humane Labs" },
    [17] = { ["object"] = "hei_prop_heist_pic_12", ["price"] = 30, ["name"] = "Motorcycle" },
    [18] = { ["object"] = "hei_prop_heist_pic_13", ["price"] = 30, ["name"] = "Jetskis" },
    [19] = { ["object"] = "hei_prop_heist_pic_14", ["price"] = 30, ["name"] = "Water" },
    [20] = { ["object"] = "prop_j_heist_pic_04", ["price"] = 30, ["name"] = "Jewelry Store" },
    [21] = { ["object"] = "prop_j_heist_pic_03", ["price"] = 30, ["name"] = "Tunnel" },
    [22] = { ["object"] = "hei_heist_acc_artgolddisc_01", ["price"] = 300, ["name"] = "Gold Disc 1" },
    [23] = { ["object"] = "hei_heist_acc_artgolddisc_02", ["price"] = 300, ["name"] = "Gold Disc 2" },
    [24] = { ["object"] = "hei_heist_acc_artgolddisc_03", ["price"] = 300, ["name"] = "Gold Disc 3" },
    [25] = { ["object"] = "hei_heist_acc_artgolddisc_04", ["price"] = 300, ["name"] = "Gold Disc 4" },
    [26] = { ["object"] = "prop_protest_sign_01", ["price"] = 100, ["name"] = "Protest Poster" },
    [27] = { ["object"] = "prop_cork_board", ["price"] = 40, ["name"] = "Cork Board" },
    [28] = { ["object"] = "prop_bank_vaultdoor", ["price"] = 8000, ["name"] = "Bank Vault" },
  },

  ["General #1"] = {
    [1] = { ["object"] = "v_res_cherubvase", ["price"] = 500, ["name"] = "White Vase" },
    [2] = { ["object"] = "v_res_d_ramskull", ["price"] = 40, ["name"] = "Animal Skull" },
    [3] = { ["object"] = "v_res_fashmag1", ["price"] = 40, ["name"] = "Mags" },
    [4] = { ["object"] = "v_res_fashmagopen", ["price"] = 50, ["name"] = "Mags Open" },
    [5] = { ["object"] = "v_res_fa_magtidy", ["price"] = 100, ["name"] = "Mag Tidy" },
    [6] = { ["object"] = "v_res_fa_yogamat002", ["price"] = 80, ["name"] = "Yoga Mat 1" },
    [7] = { ["object"] = "v_res_fa_yogamat1", ["price"] = 80, ["name"] = "Yoga Mat 2" },
    [8] = { ["object"] = "v_res_fh_aftershavebox", ["price"] = 90, ["name"] = "Aftershave" },
    [9] = { ["object"] = "v_res_fh_flowersa", ["price"] = 80, ["name"] = "Flowers" },
    [10] = { ["object"] = "v_res_fh_fruitbowl", ["price"] = 30, ["name"] = "Fruitbowl" },
    [11] = { ["object"] = "v_res_fh_laundrybasket", ["price"] = 70, ["name"] = "Laundry Basket" },
    [12] = { ["object"] = "v_res_fh_pouf", ["price"] = 100, ["name"] = "Pouf" },
    [13] = { ["object"] = "v_res_j_magrack", ["price"] = 100, ["name"] = "Mag Rack" },
    [14] = { ["object"] = "v_res_mbbin", ["price"] = 100, ["name"] = "Bin" },
    [15] = { ["object"] = "prop_cs_box_clothes", ["price"] = 80, ["name"] = "Clothes Box" },
    [16] = { ["object"] = "prop_cs_gunrack", ["price"] = 100, ["name"] = "Gun Rack" },
    [17] = { ["object"] = "v_res_mbowlornate", ["price"] = 300, ["name"] = "Ornate Bowl" },
    [18] = { ["object"] = "v_res_mbronzvase", ["price"] = 300, ["name"] = "Bronze Vase" },
    [19] = { ["object"] = "v_res_mplinth", ["price"] = 200, ["name"] = "Linth" },
    [20] = { ["object"] = "v_res_m_candle", ["price"] = 30, ["name"] = "Candle" },
    [21] = { ["object"] = "v_res_m_candlelrg", ["price"] = 50, ["name"] = "Candle Large" },
    [22] = { ["object"] = "v_res_tt_bedpillow", ["price"] = 60, ["name"] = "Bed Pillow" },
    [23] = { ["object"] = "apa_mp_h_acc_rugwooll_03", ["price"] = 200, ["name"] = "Rug 1" },
    [24] = { ["object"] = "apa_mp_h_acc_rugwoolm_04", ["price"] = 200, ["name"] = "Rug 2" },
    [25] = { ["object"] = "apa_mp_h_acc_rugwools_03", ["price"] = 200, ["name"] = "Rug 3" },
    [26] = { ["object"] = "apa_mp_h_acc_rugwoolm_02", ["price"] = 200, ["name"] = "Cool Rug" },
    [27] = { ["object"] = "prop_byard_ladder01", ["price"] = 60, ["name"] = "Wood Ladder" },
    [28] = { ["object"] = "prop_car_door_01", ["price"] = 50, ["name"] = "Car Door" },
    [29] = { ["object"] = "prop_cs_panties_02", ["price"] = 30, ["name"] = "Hanging Panties" },
    [30] = { ["object"] = "prop_idol_01", ["price"] = 100, ["name"] = "Idol 1" },
    [31] = { ["object"] = "p_cs_cuffs_02_s", ["price"] = 40, ["name"] = "Cuffs" },
    [32] = { ["object"] = "prop_michael_backpack", ["price"] = 80, ["name"] = "Backpack" },
    [33] = { ["object"] = "prop_cs_amanda_shoe", ["price"] = 20, ["name"] = "Womens Shoe" },
    [34] = { ["object"] = "prop_cs_panties", ["price"] = 60, ["name"] = "Thong" },
  },

  ["General #2"] = {
    [1] = { ["object"] = "prop_a4_pile_01", ["price"] = 30, ["name"] = "A4 Pile" },
    [2] = { ["object"] = "prop_amb_40oz_03", ["price"] = 40, ["name"] = "40 oz" },
    [3] = { ["object"] = "prop_aviators_01", ["price"] = 80, ["name"] = "Aviators" },
    [4] = { ["object"] = "prop_barry_table_detail", ["price"] = 20, ["name"] = "Detail" },
    [5] = { ["object"] = "prop_binoc_01", ["price"] = 100, ["name"] = "Binoculars" },
    [6] = { ["object"] = "prop_blox_spray", ["price"] = 40, ["name"] = "Blox Spray" },
    [7] = { ["object"] = "prop_bongos_01", ["price"] = 100, ["name"] = "Bongos" },
    [8] = { ["object"] = "prop_cs_street_binbag_01", ["price"] = 100, ["name"] = "Bin Bag" },
    [9] = { ["object"] = "prop_carrier_bag_01", ["price"] = 100, ["name"] = "Carrier bag" },
    [10] = { ["object"] = "prop_ceramic_jug_01", ["price"] = 100, ["name"] = "Ceramic Jug" },
    [11] = { ["object"] = "prop_cs_binder_01", ["price"] = 100, ["name"] = "Binder" },
    [12] = { ["object"] = "prop_cs_cashenvelope", ["price"] = 100, ["name"] = "Envelope" },
    [13] = { ["object"] = "prop_cs_sack_01", ["price"] = 100, ["name"] = "Sack" },
    [14] = { ["object"] = "prop_cs_duffel_01", ["price"] = 100, ["name"] = "Duffel Bag" },
    [15] = { ["object"] = "prop_cs_dvd", ["price"] = 50, ["name"] = "DVD" },
    [16] = { ["object"] = "prop_cs_dvd_case", ["price"] = 50, ["name"] = "DVD Case" },
    [17] = { ["object"] = "prop_cs_film_reel_01", ["price"] = 100, ["name"] = "Film Reel" },
    [18] = { ["object"] = "prop_cs_ilev_blind_01", ["price"] = 100, ["name"] = "Blind" },
    [19] = { ["object"] = "prop_cs_petrol_can", ["price"] = 100, ["name"] = "Petrol Can" },
    [20] = { ["object"] = "prop_cs_ironing_board", ["price"] = 100, ["name"] = "Ironing Board" },
    [21] = { ["object"] = "prop_cs_katana_01", ["price"] = 100, ["name"] = "Katana" },
    [22] = { ["object"] = "prop_cs_rolled_paper", ["price"] = 10, ["name"] = "Rolled Newspaper" },
    [23] = { ["object"] = "prop_cs_lester_crate", ["price"] = 100, ["name"] = "Crate" },
    [24] = { ["object"] = "prop_cs_police_torch", ["price"] = 40, ["name"] = "Flash Light" },
  },

  ["General #3"] = {
    [1] = { ["object"] = "v_ret_csr_bin", ["price"] = 30, ["name"] = "CSR Bin" },
    [2] = { ["object"] = "v_ret_fh_wickbskt", ["price"] = 50, ["name"] = "Basket" },
    [3] = { ["object"] = "v_ret_gc_bag01", ["price"] = 70, ["name"] = "GC Bag 1" },
    [4] = { ["object"] = "v_ret_gc_bag02", ["price"] = 70, ["name"] = "GC Bag 2" },
    [5] = { ["object"] = "v_ret_gc_bin", ["price"] = 50, ["name"] = "GC Bin" },
    [6] = { ["object"] = "v_ret_gc_cashreg", ["price"] = 100, ["name"] = "Cash Register" },
    [7] = { ["object"] = "v_ret_gc_chair01", ["price"] = 100, ["name"] = "GC Chair 01" },
    [8] = { ["object"] = "v_ret_gc_chair02", ["price"] = 100, ["name"] = "GC Chair 02" },
    [9] = { ["object"] = "v_ret_gc_clock", ["price"] = 100, ["name"] = "Clock" },
    [10] = { ["object"] = "v_ret_hd_prod1_", ["price"] = 10, ["name"] = "Prod 1" },
    [11] = { ["object"] = "v_ret_hd_prod2_", ["price"] = 10, ["name"] = "Prod 2" },
    [12] = { ["object"] = "v_ret_hd_prod3_", ["price"] = 10, ["name"] = "Prod 3" },
    [13] = { ["object"] = "v_ret_hd_prod4_", ["price"] = 10, ["name"] = "Prod 4" },
    [14] = { ["object"] = "v_ret_hd_prod5_", ["price"] = 10, ["name"] = "Prod 5" },
    [15] = { ["object"] = "v_ret_hd_prod6_", ["price"] = 10, ["name"] = "Prod 6" },
    [16] = { ["object"] = "v_ret_hd_unit1_", ["price"] = 100, ["name"] = "HD Unit 1" },
    [17] = { ["object"] = "v_ret_hd_unit2_", ["price"] = 100, ["name"] = "HD Unit 2" },
    [19] = { ["object"] = "v_ret_ps_bag_01", ["price"] = 100, ["name"] = "Bag 1" },
    [20] = { ["object"] = "v_ret_ps_bag_02", ["price"] = 100, ["name"] = "Bag 2" },
    [21] = { ["object"] = "v_ret_ta_book1", ["price"] = 30, ["name"] = "Book 1" },
    [22] = { ["object"] = "v_ret_ta_book2", ["price"] = 30, ["name"] = "Book 2" },
    [23] = { ["object"] = "v_ret_ta_book3", ["price"] = 30, ["name"] = "Book 3" },
    [24] = { ["object"] = "v_ret_ta_book4", ["price"] = 30, ["name"] = "Book 4" },
    [25] = { ["object"] = "v_ret_ta_camera", ["price"] = 90, ["name"] = "Cam" },
    [26] = { ["object"] = "v_ret_ta_firstaid", ["price"] = 15, ["name"] = "First Aid" },
    [27] = { ["object"] = "v_ret_ta_hero", ["price"] = 100, ["name"] = "Hero" },
    [28] = { ["object"] = "v_ret_ta_mag1", ["price"] = 50, ["name"] = "Mag 1" },
    [29] = { ["object"] = "v_ret_ta_mag2", ["price"] = 50, ["name"] = "Mag 2" },
    [30] = { ["object"] = "v_ret_ta_skull", ["price"] = 100, ["name"] = "Skull" },
    [31] = { ["object"] = "prop_acc_guitar_01", ["price"] = 100, ["name"] = "Guitar" },
    [32] = { ["object"] = "prop_amb_handbag_01", ["price"] = 100, ["name"] = "Handbag" },
    [33] = { ["object"] = "prop_attache_case_01", ["price"] = 100, ["name"] = "Case" },
    [34] = { ["object"] = "prop_big_bag_01", ["price"] = 75, ["name"] = "Big Bag" },
    [35] = { ["object"] = "prop_bonesaw", ["price"] = 50, ["name"] = "Bonesaw" },
    [36] = { ["object"] = "prop_cs_fertilizer", ["price"] = 30, ["name"] = "Fertilizer" },
    [37] = { ["object"] = "prop_cs_shopping_bag", ["price"] = 100, ["name"] = "Shopping Bag" },
    [38] = { ["object"] = "prop_cs_vial_01", ["price"] = 100, ["name"] = "Vial" },
    [39] = { ["object"] = "prop_defilied_ragdoll_01", ["price"] = 20, ["name"] = "Ragdoll" }, 
    [40] = { ["object"] = "prop_ball_box", ["price"] = 20, ["name"] = "Beach Balls" },
    [41] = { ["object"] = "prop_boogieboard_01", ["price"] = 40, ["name"] = "Rainbow Boogie" },
    [42] = { ["object"] = "prop_surf_board_ldn_04", ["price"] = 200, ["name"] = "Striped Surfboard" },
    [43] = { ["object"] = "prop_dart_bd_cab_01", ["price"] = 200, ["name"] = "Dart Board" },
    [44] = { ["object"] = "prop_box_ammo03a", ["price"] = 400, ["name"] = "Explosive Box" },
    [45] = { ["object"] = "prop_beach_bag_02", ["price"] = 30, ["name"] = "Beach Bag" },
    [46] = { ["object"] = "prop_t_telescope_01b", ["price"] = 300, ["name"] = "telescope" },
    [47] = { ["object"] = "prop_pool_rack_02", ["price"] = 200, ["name"] = "Pool Table Rack" },
    [48] = { ["object"] = "prop_gumball_03", ["price"] = 1000, ["name"] = "Gumball Machine" },
    [49] = { ["object"] = "prop_gumball_01", ["price"] = 1000, ["name"] = "Candy Dispenser" },
    [50] = { ["object"] = "prop_boogbd_stack_01", ["price"] = 100, ["name"] = "Boogie Boards" },
    [51] = { ["object"] = "prop_cs_stock_book", ["price"] = 30, ["name"] = "Book 5" },
    [52] = { ["object"] = "prop_beachbag_06", ["price"] = 30, ["name"] = "Beach Bag 2" },
    [53] = { ["object"] = "prop_beachbag_combo_02", ["price"] = 30, ["name"] = "Beach Bag Combo" },
  },

  ["General #4"] = {
    [1] = { ["object"] = "prop_dummy_01", ["price"] = 100, ["name"] = "Dummy" },
    [2] = { ["object"] = "prop_egg_clock_01", ["price"] = 100, ["name"] = "Egg Clock" },
    [3] = { ["object"] = "prop_el_guitar_01", ["price"] = 100, ["name"] = "E Guitar 1" },
    [4] = { ["object"] = "prop_el_guitar_02", ["price"] = 100, ["name"] = "E Guitar 2" },
    [5] = { ["object"] = "prop_el_guitar_03", ["price"] = 100, ["name"] = "E Guitar 2" },
    [6] = { ["object"] = "prop_feed_sack_01", ["price"] = 100, ["name"] = "Feed Sack" },
    [7] = { ["object"] = "prop_floor_duster_01", ["price"] = 100, ["name"] = "Floor Duster" },
    [8] = { ["object"] = "prop_fruit_basket", ["price"] = 100, ["name"] = "Fruit Basket" },
    [9] = { ["object"] = "prop_f_duster_02", ["price"] = 100, ["name"] = "Duster" },
    [10] = { ["object"] = "prop_grapes_02", ["price"] = 100, ["name"] = "Grapes" },
    [11] = { ["object"] = "prop_hotel_clock_01", ["price"] = 100, ["name"] = "Hotel Clock" },
    [12] = { ["object"] = "prop_bowling_pin", ["price"] = 10, ["name"] = "Bowling Pin" },
    [13] = { ["object"] = "prop_bowling_ball", ["price"] = 60, ["name"] = "Bowling Ball" },
    [14] = { ["object"] = "prop_cs_mop_s", ["price"] = 100, ["name"] = "Mop" },
    [15] = { ["object"] = "prop_cs_mopbucket_01", ["price"] = 100, ["name"] = "Mop Bucket" },
    [16] = { ["object"] = "prop_ld_greenscreen_01", ["price"] = 100, ["name"] = "Green Screen" },
    [17] = { ["object"] = "prop_ld_handbag", ["price"] = 100, ["name"] = "Handbag" },
    [18] = { ["object"] = "prop_ld_jerrycan_01", ["price"] = 100, ["name"] = "Jerry Can" },
    [19] = { ["object"] = "prop_ld_keypad_01", ["price"] = 100, ["name"] = "Keypad 1" },
    [20] = { ["object"] = "prop_ld_keypad_01b", ["price"] = 100, ["name"] = "Keypad 2" },
    [21] = { ["object"] = "prop_ld_suitcase_01", ["price"] = 100, ["name"] = "Suitcase 1" },
    [22] = { ["object"] = "prop_ld_suitcase_02", ["price"] = 100, ["name"] = "Suitcase 2" },
    [23] = { ["object"] = "hei_p_attache_case_shut", ["price"] = 100, ["name"] = "Suitcase 3"},
    [24] = { ["object"] = "prop_mr_rasberryclean", ["price"] = 100, ["name"] = "Rasberry Clean" },
    [25] = { ["object"] = "prop_paper_bag_01", ["price"] = 100, ["name"] = "Paper Bag" },
    [26] = { ["object"] = "prop_shopping_bags01", ["price"] = 100, ["name"] = "Shopping Bags" },
    [27] = { ["object"] = "prop_shopping_bags02", ["price"] = 100, ["name"] = "Shopping Bags 2" },
    [28] = { ["object"] = "prop_yoga_mat_01", ["price"] = 100, ["name"] = "Yoga Mat 1" },
    [29] = { ["object"] = "prop_yoga_mat_02", ["price"] = 100, ["name"] = "Yoga Mat 2" },
    [30] = { ["object"] = "prop_yoga_mat_03", ["price"] = 100, ["name"] = "Yoga Mat 3" },
    [31] = { ["object"] = "p_ld_sax", ["price"] = 100, ["name"] = "Sax" },
    [32] = { ["object"] = "p_ld_soc_ball_01", ["price"] = 100, ["name"] = "SOCCER Ball" },
    [33] = { ["object"] = "prop_fishing_rod_02", ["price"] = 40, ["name"] = "Fishing Rod" },
    [34] = { ["object"] = "prop_golf_bag_01b", ["price"] = 100, ["name"] = "Golf Bag" },
    [35] = { ["object"] = "prop_golf_bag_01c", ["price"] = 100, ["name"] = "Golf Bag 2" },
    [36] = { ["object"] = "prop_gun_case_01", ["price"] = 400, ["name"] = "Gun Case Closed" },
    [37] = { ["object"] = "prop_bball_arcade_01", ["price"] = 900, ["name"] = "Basketball Arcade" },
    [38] = { ["object"] = "prop_punch_bag_l", ["price"] = 100, ["name"] = "Punching Bag" },
    [39] = { ["object"] = "prop_pistol_holster", ["price"] = 80, ["name"] = "Pistol Holster" },
    [40] = { ["object"] = "prop_gun_case_02", ["price"] = 450, ["name"] = "Gun Case Open" },
  },

  ["Small"] = {
    [1] = { ["object"] = "v_res_r_figcat", ["price"] = 300, ["name"] = "Fig Cat" },
    [2] = { ["object"] = "v_res_r_figclown", ["price"] = 300, ["name"] = "Fig Clown" },
    [3] = { ["object"] = "v_res_r_figauth2", ["price"] = 300, ["name"] = "Fig Auth" },
    [4] = { ["object"] = "v_res_r_figfemale", ["price"] = 300, ["name"] = "Fig Female" },
    [5] = { ["object"] = "v_res_r_figflamenco", ["price"] = 300, ["name"] = "Fig Flamenco" },
    [6] = { ["object"] = "v_res_r_figgirl", ["price"] = 300, ["name"] = "Fig Girl" },
    [7] = { ["object"] = "v_res_r_figgirlclown", ["price"] = 300, ["name"] = "Fig Girl Clown" },
    [8] = { ["object"] = "v_res_r_figoblisk", ["price"] = 300, ["name"] = "Fig Oblisk" },
    [9] = { ["object"] = "v_res_r_figpillar", ["price"] = 300, ["name"] = "Fig Pillar" },
    [10] = { ["object"] = "v_res_r_teapot", ["price"] = 300, ["name"] = "Teapot" },
    [11] = { ["object"] = "v_res_sculpt_dec", ["price"] = 300, ["name"] = "Sculpture 1" },
    [12] = { ["object"] = "v_res_sculpt_decd", ["price"] = 300, ["name"] = "Sculpture 2" },
    [13] = { ["object"] = "v_res_sculpt_dece", ["price"] = 300, ["name"] = "Sculpture 3" },
    [14] = { ["object"] = "v_res_sculpt_decf", ["price"] = 300, ["name"] = "Sculpture 4" },
    [15] = { ["object"] = "v_res_skateboard", ["price"] = 300, ["name"] = "Skateboard" },
    [16] = { ["object"] = "v_res_sketchpad", ["price"] = 20, ["name"] = "Sketchpad" },
    [17] = { ["object"] = "v_res_tissues", ["price"] = 10, ["name"] = "Tissues" },
    [18] = { ["object"] = "v_res_tre_basketmess", ["price"] = 10, ["name"] = "Basket" },
    [19] = { ["object"] = "v_res_tre_bin", ["price"] = 30, ["name"] = "Bin" },
    [20] = { ["object"] = "v_res_tre_cushiona", ["price"] = 60, ["name"] = "Cushion 1" },
    [21] = { ["object"] = "v_res_tre_cushionb", ["price"] = 60, ["name"] = "Cushion 2" },
    [22] = { ["object"] = "v_res_tre_cushionc", ["price"] = 60, ["name"] = "Cushion 3" },
    [23] = { ["object"] = "v_res_tre_cushiond", ["price"] = 60, ["name"] = "Cushion 4" },
    [24] = { ["object"] = "v_res_tre_cushnscuzb", ["price"] = 60, ["name"] = "Cushion 5" },
    [25] = { ["object"] = "v_res_tre_cushnscuzd", ["price"] = 60, ["name"] = "Cushion 6" },
    [26] = { ["object"] = "v_res_tre_fruitbowl", ["price"] = 30, ["name"] = "Key Plate" },
    [27] = { ["object"] = "prop_devin_rope_01", ["price"] = 100, ["name"] = "Rope" },
    [28] = { ["object"] = "v_ret_gc_trays", ["price"] = 15, ["name"] = "Desk tray" },
    [29] = { ["object"] = "v_res_filebox01", ["price"] = 100, ["name"] = "File box" },
    [30] = { ["object"] = "prop_boxing_glove_01", ["price"] = 40, ["name"] = "Boxing Glove" },
    [31] = { ["object"] = "prop_cs_lipstick", ["price"] = 30, ["name"] = "Lipstick" },
    [32] = { ["object"] = "prop_fishing_rod_02", ["price"] = 40, ["name"] = "Fishing Rod" },
    [33] = { ["object"] = "prop_foundation_sponge", ["price"] = 10, ["name"] = "Foundation Sponge" },
    [34] = { ["object"] = "prop_garden_dreamcatch_01", ["price"] = 50, ["name"] = "Dream Catcher" },
    [35] = { ["object"] = "prop_golf_ball", ["price"] = 20, ["name"] = "Golf Ball" },
    [36] = { ["object"] = "prop_mem_candle_06", ["price"] = 16, ["name"] = "Candle" },
    [37] = { ["object"] = "prop_single_rose", ["price"] = 10, ["name"] = "Rose" },
    [38] = { ["object"] = "prop_table_ten_bat", ["price"] = 50, ["name"] = "Ping Pong Racket" },
    [39] = { ["object"] = "prop_armour_pickup", ["price"] = 90, ["name"] = "Bullet Vest" },
    [40] = { ["object"] = "prop_barbell_01", ["price"] = 30, ["name"] = "Barbell 1" },
    [41] = { ["object"] = "prop_barbell_02", ["price"] = 45, ["name"] = "Barbell 2" },
    [42] = { ["object"] = "prop_bskball_01", ["price"] = 65, ["name"] = "Basketball" },
    [43] = { ["object"] = "prop_snow_flower_02", ["price"] = 35, ["name"] = "Bouquet" },
    [44] = { ["object"] = "prop_snow_flower_01", ["price"] = 25, ["name"] = "Flower Wreath" },
  },

  ["Storage"] = {
    [1] = { ["object"] = "v_res_cabinet", ["price"] = 400, ["name"] = "Cabinet Large" },
    [2] = { ["object"] = "v_res_d_dressingtable", ["price"] = 500, ["name"] = "Dressing Table" },
    [3] = { ["object"] = "v_res_d_sideunit", ["price"] = 200, ["name"] = "Side Unit" },
    [4] = { ["object"] = "v_res_fh_sidebrddine", ["price"] = 600, ["name"] = "Side Unit" },
    [5] = { ["object"] = "v_res_fh_sidebrdlngb", ["price"] = 900, ["name"] = "Side Unit" },
    [6] = { ["object"] = "v_res_mbbedtable", ["price"] = 250, ["name"] = "Bed Unit" },
    [7] = { ["object"] = "v_res_j_tvstand", ["price"] = 320, ["name"] = "Tv Unit" },
    [8] = { ["object"] = "v_res_mbdresser", ["price"] = 570, ["name"] = "Dresser Unit" },
    [9] = { ["object"] = "v_res_mbottoman", ["price"] = 600, ["name"] = "Bottoman Unit" },
    [10] = { ["object"] = "v_res_mconsolemod", ["price"] = 430, ["name"] = "Console Unit" },
    [11] = { ["object"] = "v_res_mcupboard", ["price"] = 500, ["name"] = "Cupboard Unit" },
    [12] = { ["object"] = "v_res_mdchest", ["price"] = 320, ["name"] = "Chest Unit" },
    [13] = { ["object"] = "v_res_msoncabinet", ["price"] = 800, ["name"] = "Mason Unit" },
    [14] = { ["object"] = "v_res_m_armoire", ["price"] = 670, ["name"] = "Armoire Unit" },
    [15] = { ["object"] = "v_res_m_sidetable", ["price"] = 430, ["name"] = "Side Unit" },
    [16] = { ["object"] = "v_res_son_desk", ["price"] = 800, ["name"] = "Desk Unit" },
    [17] = { ["object"] = "v_res_tre_bedsidetable", ["price"] = 60, ["name"] = "Side Unit" },
    [18] = { ["object"] = "v_res_tre_bedsidetableb", ["price"] = 45, ["name"] = "Side Unit 2" },
    [19] = { ["object"] = "v_res_tre_smallbookshelf", ["price"] = 140, ["name"] = "Book Unit" },
    [20] = { ["object"] = "v_res_tre_storagebox", ["price"] = 675, ["name"] = "Box Unit" },
    [21] = { ["object"] = "v_res_tre_storageunit", ["price"] = 500, ["name"] = "Storage Unit" },
    [22] = { ["object"] = "v_res_tre_wardrobe", ["price"] = 500, ["name"] = "Wardrobe Unit" },
    [23] = { ["object"] = "v_res_tre_wdunitscuz", ["price"] = 90, ["name"] = "Wood Unit" },
    [24] = { ["object"] = "prop_devin_box_closed", ["price"] = 670, ["name"] = "Wicker Box" },
    [25] = { ["object"] = "prop_mil_crate_01", ["price"] = 400, ["name"] = "Mil Crate 1" },
    [26] = { ["object"] = "prop_mil_crate_02", ["price"] = 400, ["name"] = "Mil Crate 2" },
    [27] = { ["object"] = "prop_ld_int_safe_01", ["price"] = 500, ["name"] = "Safe" },
    [28] = { ["object"] = "prop_box_ammo01a", ["price"] = 100, ["name"] = "Ammobox" },
    [29] = { ["object"] = "prop_box_ammo07b", ["price"] = 100, ["name"] = "Ammobox2" },
    [30] = { ["object"] = "v_res_mddresser", ["price"] = 500, ["name"] = "Dresser" },
    [31] = { ["object"] = "hei_heist_str_sideboardl_05", ["price"] = 200, ["name"] = "Sideboard Dresser"},
    [31] = { ["object"] = "prop_devin_box_01", ["price"] = 670, ["name"] = "Open Box"},
    [32] = { ["object"] = "prop_coffin_02b", ["price"] = 400, ["name"] = "Coffin"},
    [33] = { ["object"] = "prop_lev_crate_01", ["price"] = 500, ["name"] = "Big Crate"},
    [34] = { ["object"] = "prop_box_tea01a", ["price"] = 400, ["name"] = "Crate of Earl Grey"},
    [35] = { ["object"] = "prop_cheetah_covered", ["price"] = 1200, ["name"] = "Covered Car"},
  },

  ["Electronics"] = {
    [1] = { ["object"] = "prop_trailr_fridge", ["price"] = 300, ["name"] = "Old Fridge" },
    [2] = { ["object"] = "v_res_fh_speaker", ["price"] = 100, ["name"] = "Speaker" },
    [3] = { ["object"] = "v_res_fh_speakerdock", ["price"] = 300, ["name"] = "Speaker Dock" },
    [4] = { ["object"] = "v_res_fh_bedsideclock", ["price"] = 90, ["name"] = "Bedside Clock" },
    [5] = { ["object"] = "v_res_fa_phone", ["price"] = 40, ["name"] = "Old School Phone" },
    [6] = { ["object"] = "v_res_fh_towerfan", ["price"] = 300, ["name"] = "Tower Fan" },
    [7] = { ["object"] = "v_res_fa_fan", ["price"] = 300, ["name"] = "Fan" },
    [8] = { ["object"] = "prop_cs_remote_01", ["price"] = 90, ["name"] = "TV Remote" },
    [9] = { ["object"] = "v_res_lest_monitor", ["price"] = 300, ["name"] = "Monitor" },
    [10] = { ["object"] = "v_res_tre_mixer", ["price"] = 300, ["name"] = "Mixer" },
    [11] = { ["object"] = "prop_cs_cctv", ["price"] = 100, ["name"] = "CCTV" },
    [12] = { ["object"] = "prop_ld_lap_top", ["price"] = 300, ["name"] = "Laptop" },
    [13] = { ["object"] = "prop_ld_monitor_01", ["price"] = 100, ["name"] = "Monitor" },
    [14] = { ["object"] = "prop_tv_flat_01", ["price"] = 2000, ["name"] = "Flatscreen TV" },
    [15] = { ["object"] = "apa_mp_h_str_avunitm_03", ["price"] = 900, ["name"] = "TV set 1" },
    [16] = { ["object"] = "apa_mp_h_str_avunits_01", ["price"] = 1300, ["name"] = "TV set 2" },
    [17] = { ["object"] = "apa_mp_h_str_avunits_04", ["price"] = 1500, ["name"] = "TV set 3" },
    [18] = { ["object"] = "bkr_prop_clubhouse_jukebox_02a", ["price"] = 1000, ["name"] = "Jukebox" },
    [19] = { ["object"] = "bkr_prop_weed_fan_floor_01a", ["price"] = 300, ["name"] = "Floor fan" },
    [20] = { ["object"] = "prop_cs_keyboard_01", ["price"] = 300, ["name"] = "Computer Keyboard" },
    [21] = { ["object"] = "prop_game_clock_02", ["price"] = 50, ["name"] = "Kronos Clock" },
    [22] = { ["object"] = "v_res_pctower", ["price"] = 800, ["name"] = "Old PC" },
    [23] = { ["object"] = "prop_vend_snak_01", ["price"] = 2000, ["name"] = "Snack Vending" },
    [24] = { ["object"] = "prop_vend_soda_02", ["price"] = 2000, ["name"] = "Sprunk Vending" },
    [25] = { ["object"] = "prop_monitor_01a", ["price"] = 600, ["name"] = "PC Monitor" },
    [26] = { ["object"] = "prop_vend_coffe_01", ["price"] = 2000, ["name"] = "Bean Vending" },
    [27] = { ["object"] = "prop_vend_soda_01", ["price"] = 2000, ["name"] = "Cola Vending" },
    [28] = { ["object"] = "prop_off_phone_01", ["price"] = 100, ["name"] = "Grey Office Phone" },
    [29] = { ["object"] = "prop_laptop_01a", ["price"] = 1000, ["name"] = "Laptop Open" },
    [30] = { ["object"] = "prop_dyn_pc", ["price"] = 1200, ["name"] = "New PC" },
    [31] = { ["object"] = "bkr_prop_money_counter", ["price"] = 100, ["name"] = "Money Counter" },
    [32] = { ["object"] = "prop_controller_01", ["price"] = 50, ["name"] = "Gaming Controller" },
    [33] = { ["object"] = "prop_monitor_01d", ["price"] = 200, ["name"] = "MonitorHub" },
    [34] = { ["object"] = "prop_tv_flat_02", ["price"] = 700, ["name"] = "Flatscreen TV 2" },
    [35] = { ["object"] = "prop_amb_phone", ["price"] = 1000, ["name"] = "Ifruit Phone" },
    [36] = { ["object"] = "prop_mouse_02", ["price"] = 80, ["name"] = "Computer mouse" },
    [37] = { ["object"] = "prop_boombox_01", ["price"] = 200, ["name"] = "Boom Box" },
    [38] = { ["object"] = "prop_cs_kettle_01", ["price"] = 80, ["name"] = "Kettle" },
    [39] = { ["object"] = "prop_console_01", ["price"] = 340, ["name"] = "Console" },
    [40] = { ["object"] = "prop_mp3_dock", ["price"] = 275, ["name"] = "Mp3 Dock" },
  },

  ["Lighting"] = {
    [1] = { ["object"] = "v_corp_cd_desklamp", ["price"] = 40, ["name"] = "Desk Corp Lamp" },
    [2] = { ["object"] = "v_res_desklamp", ["price"] = 70, ["name"] = "Desk Lamp" },
    [3] = { ["object"] = "v_res_d_lampa", ["price"] = 50, ["name"] = "Lamp AA" },
    [4] = { ["object"] = "v_res_fa_lamp1on", ["price"] = 60, ["name"] = "Lamp 1" },
    [5] = { ["object"] = "v_res_fh_floorlamp", ["price"] = 130, ["name"] = "Floor Lamp" },
    [6] = { ["object"] = "v_res_fh_lampa_on", ["price"] = 100, ["name"] = "Lamp 2" },
    [7] = { ["object"] = "v_res_j_tablelamp1", ["price"] = 30, ["name"] = "Table Lamp" },
    [8] = { ["object"] = "v_res_j_tablelamp2", ["price"] = 40, ["name"] = "Table Lamp 2" },
    [9] = { ["object"] = "v_res_mdbedlamp", ["price"] = 40, ["name"] = "Bed Lamp" },
    [10] = { ["object"] = "v_res_mtblelampmod", ["price"] = 50, ["name"] = "Table Lamp 3" },
    [11] = { ["object"] = "v_res_m_lampstand", ["price"] = 100, ["name"] = "Lamp Stand" },
    [12] = { ["object"] = "v_res_m_lampstand2", ["price"] = 120, ["name"] = "Lamp Stand 2" },
    [13] = { ["object"] = "v_res_m_lamptbl", ["price"] = 60, ["name"] = "Table Lamp 4" },
    [14] = { ["object"] = "v_res_tre_lightfan", ["price"] = 100, ["name"] = "Light Fan" },
    [15] = { ["object"] = "v_res_tre_talllamp", ["price"] = 90, ["name"] = "Tall Lamp" },
    [16] = { ["object"] = "v_ret_fh_walllighton", ["price"] = 30, ["name"] = "Wall Light" },
    [17] = { ["object"] = "v_ret_gc_lamp", ["price"] = 45, ["name"] = "GC Lamp" },
    [18] = { ["object"] = "prop_ld_cont_light_01", ["price"] = 70, ["name"] = "Side Wall Light" },
    [19] = { ["object"] = "prop_air_lights_03a", ["price"] = 100, ["name"] = "Recessed Light Bulb" },
  },

  ["Tables"] = {
    [1] = { ["object"] = "v_res_d_coffeetable", ["price"] = 80, ["name"] = "Coffee Table 1" },
    [2] = { ["object"] = "v_res_d_roundtable", ["price"] = 45, ["name"] = "Round Table" },
    [3] = { ["object"] = "v_res_d_smallsidetable", ["price"] = 50, ["name"] = "Small Side Table" },
    [4] = { ["object"] = "v_res_fh_coftablea", ["price"] = 100, ["name"] = "Table A" },
    [5] = { ["object"] = "v_res_fh_coftableb", ["price"] = 100, ["name"] = "Table B" },
    [6] = { ["object"] = "v_res_fh_coftbldisp", ["price"] = 600, ["name"] = "Table C" },
    [7] = { ["object"] = "v_res_fh_diningtable", ["price"] = 800, ["name"] = "Dining Table" },
    [8] = { ["object"] = "v_res_j_coffeetable", ["price"] = 200, ["name"] = "Coffee Table 2" },
    [9] = { ["object"] = "v_res_j_lowtable", ["price"] = 60, ["name"] = "Low Table" },
    [10] = { ["object"] = "v_res_mdbedtable", ["price"] = 70, ["name"] = "Bed Table" },
    [11] = { ["object"] = "v_res_mddesk", ["price"] = 120, ["name"] = "Desk" },
    [12] = { ["object"] = "v_res_msidetblemod", ["price"] = 80, ["name"] = "Side Table" },
    [13] = { ["object"] = "v_res_m_console", ["price"] = 110, ["name"] = "Console Table" },
    [14] = { ["object"] = "v_res_m_dinetble_replace", ["price"] = 300, ["name"] = "Dining Table 2" },
    [15] = { ["object"] = "v_res_m_h_console", ["price"] = 250, ["name"] = "Console H Table" },
    [16] = { ["object"] = "v_res_m_stool", ["price"] = 300, ["name"] = "Stool?" },
    [17] = { ["object"] = "v_res_tre_sideboard", ["price"] = 500, ["name"] = "Sideboard Table" },
    [18] = { ["object"] = "v_res_tre_table2", ["price"] = 200, ["name"] = "Table 2" },
    [19] = { ["object"] = "v_res_tre_tvstand", ["price"] = 50, ["name"] = "Tv Table" },
    [20] = { ["object"] = "v_res_tre_tvstand_tall", ["price"] = 70, ["name"] = "Tv Table Tall" },
    [21] = { ["object"] = "v_med_p_coffeetable", ["price"] = 450, ["name"] = "Med Coffee Table" },
    [22] = { ["object"] = "v_med_p_desk", ["price"] = 500, ["name"] = "Med Desk" },
    [23] = { ["object"] = "prop_yacht_table_01", ["price"] = 55, ["name"] = "Yacht Table 1" },
    [24] = { ["object"] = "prop_yacht_table_02", ["price"] = 95, ["name"] = "Yacht Table 2" },
    [25] = { ["object"] = "prop_yacht_table_03", ["price"] = 130, ["name"] = "Yacht Table 3" },
    [26] = { ["object"] = "v_ret_csr_table", ["price"] = 100, ["name"] = "CSR Table" },
    [27] = { ["object"] = "hei_heist_din_table_06", ["price"] = 800, ["name"] = "Dinner table w chairs" },
    [28] = { ["object"] = "prop_pooltable_02", ["price"] = 900, ["name"] = "Pool Table" },
    [29] = { ["object"] = "prop_table_04", ["price"] = 155, ["name"] = "Wood Table" },
    [30] = { ["object"] = "v_med_p_sideboard", ["price"] = 200, ["name"] = "Wood Tv Stand" },
    [31] = { ["object"] = "prop_fbi3_coffee_table", ["price"] = 200, ["name"] = "Wood Coffee Table" },
    [32] = { ["object"] = "ba_prop_int_edgy_table_01", ["price"] = 340, ["name"] = "Marble Coffee Table" },
    [33] = { ["object"] = "ba_prop_int_edgy_table_02", ["price"] = 440, ["name"] = "Tall Marble Round Table" },
    [34] = { ["object"] = "prop_table_tennis", ["price"] = 900, ["name"] = "Ping Pong Table" },
    [35] = { ["object"] = "prop_ff_counter_02", ["price"] = 500, ["name"] = "Stainless Steel Table" },
  },

  ["Plants"] = {
    [1] = { ["object"] = "prop_fib_plant_01", ["price"] = 150, ["name"] = "Plant Fib" },
    [2] = { ["object"] = "v_corp_bombplant", ["price"] = 70, ["name"] = "Plant Bomb" },    
    [3] = { ["object"] = "v_res_mflowers", ["price"] = 135, ["name"] = "Plant Flowers" }, 
    [4] = { ["object"] = "v_res_mvasechinese", ["price"] = 120, ["name"] = "Plant Chinese" }, 
    [5] = { ["object"] = "v_res_m_bananaplant", ["price"] = 200, ["name"] = "Plant Banana" }, 
    [6] = { ["object"] = "v_res_m_palmplant1", ["price"] = 190, ["name"] = "Plant Palm" },  
    [7] = { ["object"] = "v_res_m_palmstairs", ["price"] = 190, ["name"] = "Plant Palm 2" },  
    [8] = { ["object"] = "v_res_m_urn", ["price"] = 130, ["name"] = "Plant Urn" },  
    [9] = { ["object"] = "v_res_rubberplant", ["price"] = 120, ["name"] = "Plant Rubber" }, 
    [10] = { ["object"] = "v_res_tre_plant", ["price"] = 200, ["name"] = "Plant" }, 
    [11] = { ["object"] = "v_res_tre_tree", ["price"] = 160, ["name"] = "Plant Tree" }, 
    [12] = { ["object"] = "v_med_p_planter", ["price"] = 170, ["name"] = "Planter" }, 
    [13] = { ["object"] = "v_ret_flowers", ["price"] = 140, ["name"] = "Flowers" },
    [14] = { ["object"] = "v_ret_j_flowerdisp", ["price"] = 100, ["name"] = "Flowers 1" },
    [15] = { ["object"] = "v_ret_j_flowerdisp_white", ["price"] = 100, ["name"] = "Flowers 2" },
    [16] = { ["object"] = "apa_mp_h_acc_vase_flowers_01", ["price"] = 160, ["name"] = "Flowers 3" },
    [17] = { ["object"] = "apa_mp_h_acc_vase_flowers_02", ["price"] = 90, ["name"] = "Flowers 4" },
    [18] = { ["object"] = "xm_prop_x17_xmas_tree_int", ["price"] = 200, ["name"] = "Christmas Tree" },
    [19] = { ["object"] = "prop_plant_int_02a", ["price"] = 160, ["name"] = "Medium Tree Plant" },
    [20] = { ["object"] = "v_res_mplanttongue", ["price"] = 120, ["name"] = "Tall Plant" },
    [21] = { ["object"] = "apa_mp_h_acc_plant_tall_01", ["price"] = 120, ["name"] = "Modern Plant" },
    [22] = { ["object"] = "prop_pot_plant_01a", ["price"] = 220, ["name"] = "Little Pot Plant" },
    [23] = { ["object"] = "prop_pot_plant_01b", ["price"] = 220, ["name"] = "Little Square Plant" },
    [24] = { ["object"] = "prop_pot_plant_01c", ["price"] = 260, ["name"] = "Little Palm Plant" },
    [25] = { ["object"] = "prop_pot_plant_01d", ["price"] = 360, ["name"] = "Medium Palm Plant" },
   },

  ["Kitchen"] = {
    [1] = { ["object"] = "prop_washer_01", ["price"] = 200, ["name"] = "Washer 1" },
    [2] = { ["object"] = "prop_washer_02", ["price"] = 300, ["name"] = "Washer 2" },
    [3] = { ["object"] = "prop_washer_03", ["price"] = 250, ["name"] = "Washer 3" },
    [4] = { ["object"] = "prop_washing_basket_01", ["price"] = 40, ["name"] = "Washing Basket" },
    [5] = { ["object"] = "v_res_fridgemoda", ["price"] = 240, ["name"] = "Fridge 1" },
    [6] = { ["object"] = "v_res_fridgemodsml", ["price"] = 300, ["name"] = "Fridge 2" },
    [7] = { ["object"] = "prop_fridge_01", ["price"] = 270, ["name"] = "Fridge 3" },
    [8] = { ["object"] = "prop_fridge_03", ["price"] = 280, ["name"] = "Fridge 4" },
    [9] = { ["object"] = "prop_cooker_03", ["price"] = 400, ["name"] = "Cooker" },
    [10] = { ["object"] = "prop_micro_01", ["price"] = 150, ["name"] = "Microwave 1" },
    [11] = { ["object"] = "prop_micro_02", ["price"] = 160, ["name"] = "Microwave 2" },
    [12] = { ["object"] = "prop_wok", ["price"] = 500, ["name"] = "Wok" },
    [13] = { ["object"] = "v_res_cakedome", ["price"] = 30, ["name"] = "Cake Plate" },
    [14] = { ["object"] = "v_res_fa_chopbrd", ["price"] = 15, ["name"] = "Chopping Board" },
    [15] = { ["object"] = "v_res_mutensils", ["price"] = 10, ["name"] = "Utensils" },
    [16] = { ["object"] = "v_res_pestle", ["price"] = 10, ["name"] = "Pestle" },
    [17] = { ["object"] = "v_ret_ta_paproll", ["price"] = 15, ["name"] = "PaperRoll 1" },
    [18] = { ["object"] = "v_ret_ta_paproll2", ["price"] = 15, ["name"] = "PaperRoll 2" },
    [19] = { ["object"] = "v_ret_fh_pot01", ["price"] = 40, ["name"] = "Pot 1" },
    [20] = { ["object"] = "v_ret_fh_pot02", ["price"] = 40, ["name"] = "Pot 2" },
    [21] = { ["object"] = "v_ret_fh_pot05", ["price"] = 40, ["name"] = "Pot 3" },
    [22] = { ["object"] = "prop_pot_03", ["price"] = 40, ["name"] = "Pot 4" },
    [23] = { ["object"] = "prop_pot_04", ["price"] = 40, ["name"] = "Pot 5" },
    [24] = { ["object"] = "prop_pot_05", ["price"] = 40, ["name"] = "Pot 6" },
    [25] = { ["object"] = "prop_pot_06", ["price"] = 40, ["name"] = "Pot 7" },
    [26] = { ["object"] = "prop_pot_rack", ["price"] = 40, ["name"] = "Pot Rack" },
    [27] = { ["object"] = "prop_kitch_juicer", ["price"] = 60, ["name"] = "Juicer" },
    [28] = { ["object"] = "prop_bar_fridge_03", ["price"] = 400, ["name"] = "Mini Fridge 1" },
    [29] = { ["object"] = "prop_bar_fridge_04", ["price"] = 400, ["name"] = "Mini Fridge 2" },
    [30] = { ["object"] = "prop_bar_cooler_01", ["price"] = 400, ["name"] = "Bar Cooler" },
    [31] = { ["object"] = "prop_bar_ice_01", ["price"] = 400, ["name"] = "Bar Ice Chest" },
    [32] = { ["object"] = "prop_watercooler", ["price"] = 100, ["name"] = "Water Dispenser" },
    [33] = { ["object"] = "prop_keg_01", ["price"] = 100, ["name"] = "Keg" },
    [34] = { ["object"] = "v_ret_ml_beerpis2", ["price"] = 25, ["name"] = "Pib 12pk" },
    [35] = { ["object"] = "ba_prop_battle_bar_fridge_01", ["price"] = 400, ["name"] = "Tall Wine Fridge" },
    [36] = { ["object"] = "prop_bar_sink_01", ["price"] = 500, ["name"] = "Industrial Sink" },
    [37] = { ["object"] = "v_res_mkniferack", ["price"] = 80, ["name"] = "Wall Knife Rack" },
    [38] = { ["object"] = "v_res_mchopboard", ["price"] = 25, ["name"] = "Kitchen Cutting Board" },
    [39] = { ["object"] = "prop_slush_dispenser", ["price"] = 1000, ["name"] = "Slushy Machine" },
    [40] = { ["object"] = "prop_food_bs_soda_01", ["price"] = 1000, ["name"] = "Soda Fountain" },
    [41] = { ["object"] = "prop_juice_dispenser", ["price"] = 100, ["name"] = "Juice Dispenser" },
    [42] = { ["object"] = "prop_coffee_mac_02", ["price"] = 400, ["name"] = "Coffee Machine Drip" },
    [43] = { ["object"] = "v_res_tt_cereal02", ["price"] = 8, ["name"] = "Cereal" },
    [44] = { ["object"] = "v_res_tt_milk", ["price"] = 5, ["name"] = "Milk" },
    [45] = { ["object"] = "ex_mp_h_acc_coffeemachine_01", ["price"] = 500, ["name"] = "Coffeemachine" },
    [46] = { ["object"] = "v_ret_ml_fridge02", ["price"] = 30, ["name"] = "Old Fridge" },
    [47] = { ["object"] = "prop_breadbin_01", ["price"] = 20, ["name"] = "Bread Bin" },
    [48] = { ["object"] = "prop_ff_sink_02", ["price"] = 400, ["name"] = "Stainless Kitchen Sink" },
    [49] = { ["object"] = "prop_cleaver", ["price"] = 40, ["name"] = "cleaver" },
  },

  ["Bathroom"] = {
    [1] = { ["object"] = "prop_ld_toilet_01", ["price"] = 60, ["name"] = "Old Toilet" },
    [2] = { ["object"] = "prop_toilet_01", ["price"] = 90, ["name"] = "New Toilet" },
    [3] = { ["object"] = "prop_toilet_02", ["price"] = 100, ["name"] = "Modern Toilet" },
    [4] = { ["object"] = "prop_sink_02", ["price"] = 100, ["name"] = "Modern Sink" },
    [5] = { ["object"] = "prop_sink_04", ["price"] = 130, ["name"] = "Laundry Room Sink" },
    [6] = { ["object"] = "prop_sink_05", ["price"] = 50, ["name"] = "Round Sink" },
    [7] = { ["object"] = "prop_sink_06", ["price"] = 80, ["name"] = "Standard Sink" },
    [8] = { ["object"] = "prop_soap_disp_01", ["price"] = 30, ["name"] = "Soap Dispenser" },
    [9] = { ["object"] = "prop_shower_rack_01", ["price"] = 45, ["name"] = "Shower Rack" },
    [10] = { ["object"] = "prop_handdry_01", ["price"] = 55, ["name"] = "Paper Towel" },
    [11] = { ["object"] = "prop_handdry_02", ["price"] = 75, ["name"] = "Hand Dryer" },
    [12] = { ["object"] = "prop_towel_rail_01", ["price"] = 40, ["name"] = "Big Towel Rail" },
    [13] = { ["object"] = "prop_towel_rail_02", ["price"] = 20, ["name"] = "Small Towel Rail" },
    [14] = { ["object"] = "prop_towel_01", ["price"] = 30, ["name"] = "Medium Towels" },
    [15] = { ["object"] = "v_res_mbtowel", ["price"] = 25, ["name"] = "Towel" },
    [16] = { ["object"] = "v_res_mbtowelfld", ["price"] = 20, ["name"] = "Small Towels" },
    [17] = { ["object"] = "v_res_mbath", ["price"] = 500, ["name"] = "Bath" },
    [18] = { ["object"] = "v_res_mbsink", ["price"] = 130, ["name"] = "Fancy Sink" },
    [19] = { ["object"] = "prop_toothpaste_01", ["price"] = 8, ["name"] = "Toothpaste" },
    [20] = { ["object"] = "prop_toothbrush_01", ["price"] = 10, ["name"] = "Toothbrush" },
    [21] = { ["object"] = "prop_toilet_roll_01", ["price"] = 12, ["name"] = "Toilet Paper" },
    [22] = { ["object"] = "prop_ftowel_07", ["price"] = 25, ["name"] = "Towels" },
    [23] = { ["object"] = "prop_ftowel_10", ["price"] = 25, ["name"] = "Towels 2" },
  },

  ["Medical"] = {
    [1] = { ["object"] = "v_med_barrel", ["price"] = 200, ["name"] = "Barrel" },
    [2] = { ["object"] = "v_med_apecrate", ["price"] = 300, ["name"] = "Ape Crate" },
    [3] = { ["object"] = "v_med_apecratelrg", ["price"] = 550, ["name"] = "Ape Crate Large" },
    [4] = { ["object"] = "v_med_bed1", ["price"] = 500, ["name"] = "Bed 1" },
    [5] = { ["object"] = "v_med_bed2", ["price"] = 650, ["name"] = "Bed 2" },
    [6] = { ["object"] = "v_med_bedtable", ["price"] = 70, ["name"] = "Bed Table" },
    [7] = { ["object"] = "v_med_bench1", ["price"] = 450, ["name"] = "Bench 1" },
    [8] = { ["object"] = "v_med_bench2", ["price"] = 550, ["name"] = "Bench 2" },
    [9] = { ["object"] = "v_med_benchcentr", ["price"] = 650, ["name"] = "Bench Center" },
    [10] = { ["object"] = "v_med_benchset1", ["price"] = 700, ["name"] = "Bench Set" },
    [11] = { ["object"] = "v_med_bigtable", ["price"] = 750, ["name"] = "Big Table" },
    [12] = { ["object"] = "v_med_bin", ["price"] = 50, ["name"] = "Bin" },
    [13] = { ["object"] = "v_med_centrifuge1", ["price"] = 150, ["name"] = "Centrifuge" },
    [14] = { ["object"] = "v_med_cooler", ["price"] = 200, ["name"] = "Cooler" },
    [15] = { ["object"] = "v_med_cor_ceilingmonitor", ["price"] = 240, ["name"] = "Monitor" },
    [16] = { ["object"] = "v_med_cor_autopsytbl", ["price"] = 750, ["name"] = "Autopsy Table" },
    [17] = { ["object"] = "v_med_cor_cembin", ["price"] = 30, ["name"] = "Bin" },
    [18] = { ["object"] = "v_med_cor_cemtrolly2", ["price"] = 150, ["name"] = "Trolley" },
    [19] = { ["object"] = "v_med_cor_chemical", ["price"] = 40, ["name"] = "Chem" },
    [20] = { ["object"] = "v_med_cor_emblmtable", ["price"] = 750, ["name"] = "BLM Table" },
    [21] = { ["object"] = "v_med_cor_fileboxa", ["price"] = 30, ["name"] = "File Box" },
    [22] = { ["object"] = "v_med_cor_filingcab", ["price"] = 200, ["name"] = "File Cab" },
    [23] = { ["object"] = "v_med_cor_hose", ["price"] = 140, ["name"] = "Hose" },
    [24] = { ["object"] = "v_med_cor_largecupboard", ["price"] = 650, ["name"] = "Large Cupboard" },
    [25] = { ["object"] = "v_med_cor_lightbox", ["price"] = 350, ["name"] = "Lightbox" },
    [26] = { ["object"] = "v_med_cor_medstool", ["price"] = 80, ["name"] = "Medstool" },
    [27] = { ["object"] = "v_med_cor_minifridge", ["price"] = 200, ["name"] = "Minifridge" },
    [28] = { ["object"] = "v_med_cor_papertowels", ["price"] = 20, ["name"] = "Papertowels" },
    [29] = { ["object"] = "v_med_cor_photocopy", ["price"] = 400, ["name"] = "Photocopy" },
    [30] = { ["object"] = "v_med_cor_tvstand", ["price"] = 500, ["name"] = "TV Stand" },
    [31] = { ["object"] = "v_med_cor_wallunita", ["price"] = 470, ["name"] = "Wall Unit" },
    [32] = { ["object"] = "v_med_examlight", ["price"] = 200, ["name"] = "Exam light" },
    [33] = { ["object"] = "v_med_gastank", ["price"] = 350, ["name"] = "Gas Tank" },
    [34] = { ["object"] = "v_med_hazmatscan", ["price"] = 160, ["name"] = "Hazmat Scan" },
    [35] = { ["object"] = "v_med_hospheadwall1", ["price"] = 250, ["name"] = "Head Wall" },
    [36] = { ["object"] = "v_med_hospseating1", ["price"] = 280, ["name"] = "Seating" },
    [37] = { ["object"] = "v_med_hosptable", ["price"] = 130, ["name"] = "Hosp Table" },
    [38] = { ["object"] = "v_med_latexgloveboxblue", ["price"] = 18, ["name"] = "Glove Box" },
    [39] = { ["object"] = "v_med_medwastebin", ["price"] = 20, ["name"] = "Wastebin" },
    [40] = { ["object"] = "v_med_oscillator3", ["price"] = 100, ["name"] = "Oscillator" },
    [41] = { ["object"] = "prop_ld_health_pack", ["price"] = 40, ["name"] = "Health Pack" },
    [42] = { ["object"] = "prop_fire_exting_2a", ["price"] = 80, ["name"] = "Fire Extinguisher" },
  },

  ["PERMANENT"] = {
    [1] = { ["object"] = "prop_cs_dildo_01", ["price"] = 100, ["name"] = "Good vibes" },
    [2] = { ["object"] = "v_res_d_dildo_a", ["price"] = 100, ["name"] = "Good vibes 2" },
    [3] = { ["object"] = "v_res_d_dildo_b", ["price"] = 100, ["name"] = "Good vibes 3" },
    [4] = { ["object"] = "v_res_d_dildo_c", ["price"] = 100, ["name"] = "Good vibes 4" },
    [5] = { ["object"] = "prop_barrachneon", ["price"] = 500, ["name"] = "Neon Beer Sign 1" },
    [6] = { ["object"] = "prop_beer_neon_02", ["price"] = 500, ["name"] = "Neon Beer Sign 2" },
    [7] = { ["object"] = "prop_beer_neon_03", ["price"] = 500, ["name"] = "Neon Beer Sign 3" },
    [8] = { ["object"] = "prop_beer_neon_04", ["price"] = 500, ["name"] = "Neon Beer Sign 4" },
    [9] = { ["object"] = "prop_beerneon", ["price"] = 500, ["name"] = "Neon Beer Sign 5" },
    [10] = { ["object"] = "prop_cherenneon", ["price"] = 500, ["name"] = "Neon Cherenkov Sign" },
    [11] = { ["object"] = "prop_cockneon", ["price"] = 500, ["name"] = "Neon Cocktail Sign" },
    [12] = { ["object"] = "prop_loggneon", ["price"] = 500, ["name"] = "Neon Logger Sign" },
    [13] = { ["object"] = "prop_patriotneon", ["price"] = 500, ["name"] = "Neon Patriot Sign" },
    [14] = { ["object"] = "prop_ragganeon", ["price"] = 500, ["name"] = "Neon Ragga Sign" },
    [15] = { ["object"] = "prop_irish_sign_06", ["price"] = 300, ["name"] = "Irish Sign" },
    [16] = { ["object"] = "v_res_d_paddedwall", ["price"] = 200, ["name"] = "Padded Wall" },
    [17] = { ["object"] = "v_res_fh_sculptmod", ["price"] = 300, ["name"] = "Sculpture" },
    [18] = { ["object"] = "v_res_d_lube", ["price"] = 20, ["name"] = "Lube" },
    [19] = { ["object"] = "v_res_d_whips", ["price"] = 140, ["name"] = "Whips" },
    [20] = { ["object"] = "prop_ld_tooth", ["price"] = 100, ["name"] = "Tooth" },
    [21] = { ["object"] = "prop_arc_blueprints_01", ["price"] = 50, ["name"] = "Blueprints" },
    [22] = { ["object"] = "prop_ing_camera_01", ["price"] = 505, ["name"] = "Camera" },
    [23] = { ["object"] = "prop_bumper_04", ["price"] = 100, ["name"] = "Car Bumper" },
    [24] = { ["object"] = "patoche_cons4", ["price"] = 400, ["name"] = "Nintendo switch" },
    [25] = { ["object"] = "patoche_cons9", ["price"] = 400, ["name"] = "Gamecube" },
    [26] = { ["object"] = "patoche_cons1", ["price"] = 400, ["name"] = "PS5" },
    [27] = { ["object"] = "patoche_cons8", ["price"] = 100, ["name"] = "PS Controller" },
    [28] = { ["object"] = "v_res_pcheadset", ["price"] = 200, ["name"] = "Gaming Headset" },
    [29] = { ["object"] = "ch_prop_arcade_claw_plush_04a", ["price"] = 500, ["name"] = "Cute Plushie Toy" },
    [30] = { ["object"] = "patoche_cyber_arm5", ["price"] = 5000, ["name"] = "Fortnite Sniper" },
    [31] = { ["object"] = "patoche_cons2", ["price"] = 400, ["name"] = "New Xbox" },
    [32] = { ["object"] = "patoche_cons3", ["price"] = 300, ["name"] = "Docked Switch" },
    [33] = { ["object"] = "patoche_cons6", ["price"] = 100, ["name"] = "Switch Joystick Right" },
    [34] = { ["object"] = "patoche_cons5", ["price"] = 100, ["name"] = "Switch Joystick Left" },
    [35] = { ["object"] = "patoche_cons7", ["price"] = 200, ["name"] = "PS2" },
    [36] = { ["object"] = "patoche_carac7", ["price"] = 5000, ["name"] = "Iron Man Coffee Table" },
    [37] = { ["object"] = "patoche_carac12", ["price"] = 2000, ["name"] = "Ahri" },
    [38] = { ["object"] = "patoche_cyber_objet1", ["price"] = 3000, ["name"] = "Custom Gaming PC" },
    [39] = { ["object"] = "patoche_cyber_arm1", ["price"] = 5000, ["name"] = "Valorant Gun" },
    [40] = { ["object"] = "patoche_cyber_bou10", ["price"] = 300, ["name"] = "Link Shield" },
    [41] = { ["object"] = "patoche_cyber_bou9", ["price"] = 300, ["name"] = "Link Shield 2" },
    [42] = { ["object"] = "patoche_carac6", ["price"] = 400, ["name"] = "Little Spiderman Figure" },
    [43] = { ["object"] = "patoche_carac10", ["price"] = 5000, ["name"] = "Capt America Shield" },
    [44] = { ["object"] = "prop_dummy_light", ["price"] = 35, ["name"] = "Flickering Light" },  
  },
}

lookuptable = {}
dropdowntable = {}
hashtable = {}

for category,v in pairs(furni.objects) do 
  dropdowntable[category] = {}

  for o,k in pairs(v) do

    local hash = GetHashKey(k.object)
    hashtable[hash] = k
  
    local id = k.object or "none"
    local name = k.name or "none"
    local price = k.price or 9999

    lookuptable[id] = k

    table.insert(dropdowntable[category],{id = id,name = name,price = price})
  end 
end 

for k,v in pairs(furni.objects) do
  for k,v in pairs(v) do
    v.id = v.object
  end
end

if not Config.UsingNativeHousing then
  TriggerEvent('esx:getSharedObject', function(obj) ESX = obj; end)
  Citizen.CreateThread(function(...) while not ESX do TriggerEvent('esx:getSharedObject',function(obj) ESX = obj; end); Citizen.Wait(0); end; end)
end

mLibs = exports["meta_libs"]