-------------------------------------
------- Created by T1GER#9080 -------
------------------------------------- 

Lang = {
  -- GENERAL:
  ['no_players_nearby']         = 'No players nearby',
  ['car_locked']         		= 'You ~r~locked~s~ your car',
  ['car_unlocked']         		= 'You ~g~unlocked~s~ your car',
  ['no_veh_nearby']         	= 'No vehicle nearby',
  ['has_key_false']         	= 'You don\'t have keys for that car',
  ['menu_return']         		= 'Return',
  ['police_notify']         	= '^0ongoing grand theft auto at ^3%s^0',
  ['dispatch_name']         	= '^5 Dispatch: ',
  ['lockpick_fail']         	= 'Lockpicking Failed',
  ['lockpick_success']         	= 'You successfully ~y~lockpicked~s~ the vehicle',
  ['hotwire_fail']         		= 'Hotwiring Failed, try again',
  ['hotwire_success']         	= 'You successfully ~y~hotwired~s~ the vehicle',
  ['not_in_drv_seat']         	= 'You have to sit on the driver\'s seat',
  ['hotwire_impossible']      	= 'This vehicle does not require hotwiring!',
  ['search_impossible']      	= 'You cannot search this vehicle',
  ['not_in_a_veh']      		= 'You are not sitting in a vehicle',
  ['npc_give_keys']      		= 'You received a pair of keys for the vehicle',
  ['npc_ran_away']      		= 'The NPC ran away with the keys',
  ['cash_found']      			= 'You found ~g~$%s~s~ in cash.',
  ['item_found']      			= 'You found ~b~%sx~s~ ~y~%s~s~.',
  
  -- LOCKSMITH MENU:
  ['open_locksmith']            = '~r~[E]~s~ FOR ~y~LOCKSMITH~s~',
  ['shop_main_title']           = 'Select a Car',
  ['reg_key_title']           	= 'Register Key Price: $%s',
  ['reg_key_accept']           	= 'Accept',
  ['reg_key_decline']           = 'Decline',
  ['key_reg_accepted']          = 'You registered a new pair of keys for the selected vehicle',
  ['key_reg_declined']          = 'You declined to register a key for the selected vehicle',
    
  -- ALARMSHOP MENU:
  ['open_alarmshop']            = '~r~[E]~s~ FOR ~y~ALARM SHOP~s~',
  ['alarm_main_title']          = 'Select a Car',
  ['alarm_grade_0']          	= 'Remove Alarm',
  ['alarm_grade_1']          	= 'Alarm I',
  ['alarm_grade_2']          	= 'Alarm II',
  ['alarm_select_title']        = 'Select an Alarm',
  ['alarm_already_owned']       = 'You already owned this alarm type',
  ['alarm_removed']       		= 'You removed your alarm for that vehicle',
  ['alarm_I_purchased']       	= 'You purhcased Alarm I for your vehicle',
  ['alarm_II_purchased']       	= 'You purhcased Alarm II for your vehicle',
  ['not_enough_money']       	= 'You don\'t have enough money',
  ['remove_not_exist_alarm']    = 'You cannot remove an alarm you don\'t have',
  ['smth_went_wrong']       = 'Contact staff, couldnt find plate in DB',
  
  -- CAR MENU:
  ['car_menu_title']          	= 'Car Menu',
  ['your_keys']          		= 'Your Keys',
  ['confirm_giving_key']        = 'Confirm to give keys?',
  ['confirm_choice']          	= 'Yes',
  ['decline_choice']          	= 'No',
  ['remove_key']          	    = 'Remove Key',
  ['insured_cars_title']        = 'Your Insured Cars',
  ['veh_windows_menu']          = 'Windows Options',
  ['veh_door_menu']          	= 'Doors Options',
  ['veh_engine_label']          = 'Engine On/Off',
  ['veh_neon_label']          	= 'Neon On/Off',
  ['insurance_menu']          	= 'Insured Cars',
  ['no_insured_cars']          	= 'You don\'t have any insured cars!',
  ['eng_not_running']          	= 'Engine must be running!',
  ['veh_door_menu_title']       = 'Open/Close Door',
  ['veh_windows_menu_title']    = 'Windows Up/Down',
  ['door_hood']      			= 'Hood',
  ['door_trunk']       			= 'Trunk',
  ['door_front_left']       	= 'Front Door (L)',
  ['door_front_right']       	= 'Front Door (R)',
  ['door_rear_left']       		= 'Rear Door (L)',
  ['door_rear_right']       	= 'Rear Door (R)',
  ['window_front_r']       		= 'Front Window (L)',
  ['window_front_l']       		= 'Front Window (R)',
  ['window_rear_r']       		= 'Rear Window (L)',
  ['window_rear_l']       		= 'Rear Window (R)',
    
  -- YOUR KEYS MENU:
  ['your_keys_title']          	= 'Your Keys',
  ['keys_lend_give']          	= 'You lended out your car keys to the nearby player',
  ['keys_lend_receive']         = 'You received car keys from nearby player',
  ['keys_not_stolen_keys']      = 'You cannot lend out stolen keys',
  ['keys_not_copy_keys']        = 'You cannot lend out copy keys',
  ['cannot_remove_owned_keys']  = 'You cannot remove your owned car keys',
  
}
